import type { Icon } from '@icon-park/react/lib/runtime';

export {
  DownOne as TriangleDownIcon,
  Find as FindIcon,
  FontSizeTwo as FontSizeIcon,
  List as ListCheckboxIcon,
  ListOne as ListUnorderedIcon,
  OrderedList as ListOrderedIcon,
  Redo as RedoIcon,
  RightOne as TriangleRightIcon,
  Strikethrough as StrikethroughIcon,
  AddText as TextIcon,
  TextBold as BoldIcon,
  TextItalic as ItalicIcon,
  TextUnderline as UnderlineIcon,
  Undo as UndoIcon,
  Plus as PlusIcon,
  Pound as HashIcon,
  Translate as Text1Icon,
  FullSelection as MultiSelectIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowRight as ArrowRightIcon,
  Delete as TrashIcon,
} from '@icon-park/react';
