/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'palette.black': '#1b1f24',
  'palette.white': '#ffffff',
  'palette.gray0': '#f2f4f8',
  'palette.gray1': '#eceff4',
  'palette.gray2': '#e5e9f0',
  'palette.gray3': '#e5e9f0',
  'palette.gray4': '#afb8c1',
  'palette.gray5': '#6e7781',
  'palette.gray6': '#4c566a',
  'palette.gray7': '#434c5e',
  'palette.gray8': '#434c5e',
  'palette.gray9': '#2e3440',
  'palette.green0': '#dafbe1',
  'palette.green1': '#aceebb',
  'palette.green2': '#6fdd8b',
  'palette.green3': '#4ac26b',
  'palette.green4': '#2da44e',
  'palette.green5': '#1a7f37',
  'palette.green6': '#116329',
  'palette.green7': '#044f1e',
  'palette.green8': '#003d16',
  'palette.green9': '#002d11',
  'palette.blue0': '#ddf4ff',
  'palette.blue1': '#b6e3ff',
  'palette.blue2': '#80ccff',
  'palette.blue3': '#54aeff',
  'palette.blue4': '#218bff',
  'palette.blue5': '#0969da',
  'palette.blue6': '#0550ae',
  'palette.blue7': '#033d8b',
  'palette.blue8': '#0a3069',
  'palette.blue9': '#002155',
  'palette.coral0': '#fff0eb',
  'palette.coral1': '#ffd6cc',
  'palette.coral2': '#ffb4a1',
  'palette.coral3': '#fd8c73',
  'palette.coral4': '#ec6547',
  'palette.coral5': '#c4432b',
  'palette.coral6': '#9e2f1c',
  'palette.coral7': '#801f0f',
  'palette.coral8': '#691105',
  'palette.coral9': '#510901',
  'palette.red0': '#ffebe9',
  'palette.red1': '#ffcecb',
  'palette.red2': '#ffaba8',
  'palette.red3': '#ff8182',
  'palette.red4': '#fa4549',
  'palette.red5': '#cf222e',
  'palette.red6': '#a40e26',
  'palette.red7': '#82071e',
  'palette.red8': '#660018',
  'palette.red9': '#4c0014',
  'color.background': '#f2f4f8',
  'color.text.error': '#82071e',
  'color.text.link': '#0969da',
  'spacing.spacer0': '0',
  'spacing.spacerXs': '4px',
  'spacing.spacerS': '8px',
  'spacing.spacerM': '16px',
  'spacing.spacerX': '24px',
  'spacing.spacerXl': '32px',
  'spacing.spacerXxl': '40px',
  'font.family.system': [
    '-apple-system,',
    'BlinkMacSystemFont',
    'Segoe UI',
    'Helvetica',
    'Arial',
    'sans-serif',
    'Apple Color Emoji',
    'Segoe UI Emoji',
  ],
  'font.family.monospace': [
    'SFMono-Regular',
    'Consolas',
    'Liberation Mono',
    'Menlo',
    'Courier',
    'monospace',
  ],
  'font.family.display': [
    'InterUI',
    '-apple-system',
    'BlinkMacSystemFont',
    'Helvetica Neue',
    'Segoe UI',
    'Oxygen',
    'Ubuntu',
    'Cantarell',
    'Open Sans',
    'sans-serif',
  ],
  'font.family.size.f00': '32px',
  'font.family.size.f0': '32px',
  'font.family.size.f1': '26px',
  'font.family.size.f2': '22px',
  'font.family.size.f3': '16px',
  'font.family.size.f4': '16px',
  'font.family.size.f5': '14px',
  'font.family.size.f6': '12px',
  'font.family.lineHeight.default': '1.5',
  'font.family.lineHeight.condensed': '1.25',
  'font.family.lineHeight.condensedUltra': '1',
};

export const meta = {
  'palette.black': {
    _original: {
      $value: '#1b1f24',
      $extensions: {
        mode: {
          light: '#1b1f24',
          'light-high-contrast': '#010409',
          dark: '#010409',
          white: '#f0f6fc',
          'dark-dimmed': '#1c2128',
          'dark-high-contrast': '#010409',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.black',
    $type: 'color',
    $value: '#1b1f24',
    $extensions: {
      mode: {
        light: '#1b1f24',
        'light-high-contrast': '#010409',
        dark: '#010409',
        white: '#f0f6fc',
        'dark-dimmed': '#1c2128',
        'dark-high-contrast': '#010409',
      },
    },
  },
  'palette.white': {
    _original: {
      $value: '#ffffff',
      $extensions: {
        mode: {
          light: '#ffffff',
          'light-high-contrast': '#ffffff',
          dark: '#f0f6fc',
          'dark-dimmed': '#cdd9e5',
          'dark-high-contrast': '#ffffff',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.white',
    $type: 'color',
    $value: '#ffffff',
    $extensions: {
      mode: {
        light: '#ffffff',
        'light-high-contrast': '#ffffff',
        dark: '#f0f6fc',
        'dark-dimmed': '#cdd9e5',
        'dark-high-contrast': '#ffffff',
      },
    },
  },
  'palette.gray0': {
    _original: {
      $value: '#f2f4f8',
      $extensions: {
        mode: {
          light: '#f2f4f8',
          'light-high-contrast': '#FFFFFF',
          dark: '#f0f6fc',
          'dark-dimmed': '#cdd9e5',
          'dark-high-contrast': '#ffffff',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray0',
    $type: 'color',
    $value: '#f2f4f8',
    $extensions: {
      mode: {
        light: '#f2f4f8',
        'light-high-contrast': '#ffffff',
        dark: '#f0f6fc',
        'dark-dimmed': '#cdd9e5',
        'dark-high-contrast': '#ffffff',
      },
    },
  },
  'palette.gray1': {
    _original: {
      $value: '#ECEFF4',
      $extensions: {
        mode: {
          light: '#ECEFF4',
          'light-high-contrast': '#E7ECF0',
          dark: '#c9d1d9',
          'dark-dimmed': '#adbac7',
          'dark-high-contrast': '#f0f3f6',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray1',
    $type: 'color',
    $value: '#eceff4',
    $extensions: {
      mode: {
        light: '#eceff4',
        'light-high-contrast': '#e7ecf0',
        dark: '#c9d1d9',
        'dark-dimmed': '#adbac7',
        'dark-high-contrast': '#f0f3f6',
      },
    },
  },
  'palette.gray2': {
    _original: {
      $value: '#E5E9F0',
      $extensions: {
        mode: {
          light: '#E5E9F0',
          'light-high-contrast': '#CED5DC',
          dark: '#b1bac4',
          'dark-dimmed': '#909dab',
          'dark-high-contrast': '#d9dee3',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray2',
    $type: 'color',
    $value: '#e5e9f0',
    $extensions: {
      mode: {
        light: '#e5e9f0',
        'light-high-contrast': '#ced5dc',
        dark: '#b1bac4',
        'dark-dimmed': '#909dab',
        'dark-high-contrast': '#d9dee3',
      },
    },
  },
  'palette.gray3': {
    _original: {
      $value: '#E5E9F0',
      $extensions: {
        mode: {
          light: '#E5E9F0',
          'light-high-contrast': '#ACB6C0',
          dark: '#8b949e',
          'dark-dimmed': '#768390',
          'dark-high-contrast': '#bdc4cc',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray3',
    $type: 'color',
    $value: '#e5e9f0',
    $extensions: {
      mode: {
        light: '#e5e9f0',
        'light-high-contrast': '#acb6c0',
        dark: '#8b949e',
        'dark-dimmed': '#768390',
        'dark-high-contrast': '#bdc4cc',
      },
    },
  },
  'palette.gray4': {
    _original: {
      $value: '#afb8c1',
      $extensions: {
        mode: {
          light: '#afb8c1',
          'light-high-contrast': '#88929D',
          dark: '#6e7681',
          'dark-dimmed': '#636e7b',
          'dark-high-contrast': '#9ea7b3',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray4',
    $type: 'color',
    $value: '#afb8c1',
    $extensions: {
      mode: {
        light: '#afb8c1',
        'light-high-contrast': '#88929d',
        dark: '#6e7681',
        'dark-dimmed': '#636e7b',
        'dark-high-contrast': '#9ea7b3',
      },
    },
  },
  'palette.gray5': {
    _original: {
      $value: '#6e7781',
      $extensions: {
        mode: {
          light: '#6e7781',
          'light-high-contrast': '#66707B',
          dark: '#484f58',
          'dark-dimmed': '#545d68',
          'dark-high-contrast': '#7a828e',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray5',
    $type: 'color',
    $value: '#6e7781',
    $extensions: {
      mode: {
        light: '#6e7781',
        'light-high-contrast': '#66707b',
        dark: '#484f58',
        'dark-dimmed': '#545d68',
        'dark-high-contrast': '#7a828e',
      },
    },
  },
  'palette.gray6': {
    _original: {
      $value: '#4C566A',
      $extensions: {
        mode: {
          light: '#4C566A',
          'light-high-contrast': '#4B535D',
          dark: '#30363d',
          'dark-dimmed': '#444c56',
          'dark-high-contrast': '#525964',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray6',
    $type: 'color',
    $value: '#4c566a',
    $extensions: {
      mode: {
        light: '#4c566a',
        'light-high-contrast': '#4b535d',
        dark: '#30363d',
        'dark-dimmed': '#444c56',
        'dark-high-contrast': '#525964',
      },
    },
  },
  'palette.gray7': {
    _original: {
      $value: '#434C5E',
      $extensions: {
        mode: {
          light: '#434C5E',
          'light-high-contrast': '#343B43',
          dark: '#21262d',
          'dark-dimmed': '#373e47',
          'dark-high-contrast': '#272b33',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray7',
    $type: 'color',
    $value: '#434c5e',
    $extensions: {
      mode: {
        light: '#434c5e',
        'light-high-contrast': '#343b43',
        dark: '#21262d',
        'dark-dimmed': '#373e47',
        'dark-high-contrast': '#272b33',
      },
    },
  },
  'palette.gray8': {
    _original: {
      $value: '#434C5E',
      $extensions: {
        mode: {
          light: '#434C5E',
          'light-high-contrast': '#20252C',
          dark: '#161b22',
          'dark-dimmed': '#2d333b',
          'dark-high-contrast': '#272b33',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray8',
    $type: 'color',
    $value: '#434c5e',
    $extensions: {
      mode: {
        light: '#434c5e',
        'light-high-contrast': '#20252c',
        dark: '#161b22',
        'dark-dimmed': '#2d333b',
        'dark-high-contrast': '#272b33',
      },
    },
  },
  'palette.gray9': {
    _original: {
      $value: '#2E3440',
      $extensions: {
        mode: {
          light: '#2E3440',
          'light-high-contrast': '#0E1116',
          dark: '#0d1117',
          'dark-dimmed': '#22272e',
          'dark-high-contrast': '#0a0c10',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.gray9',
    $type: 'color',
    $value: '#2e3440',
    $extensions: {
      mode: {
        light: '#2e3440',
        'light-high-contrast': '#0e1116',
        dark: '#0d1117',
        'dark-dimmed': '#22272e',
        'dark-high-contrast': '#0a0c10',
      },
    },
  },
  'palette.green0': {
    _original: {
      $value: '#dafbe1',
      $extensions: {
        mode: {
          light: '#dafbe1',
          'light-high-contrast': '#d2fedb',
          dark: '#aff5b4',
          'dark-dimmed': '#b4f1b4',
          'dark-high-contrast': '#acf7b6',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green0',
    $type: 'color',
    $value: '#dafbe1',
    $extensions: {
      mode: {
        light: '#dafbe1',
        'light-high-contrast': '#d2fedb',
        dark: '#aff5b4',
        'dark-dimmed': '#b4f1b4',
        'dark-high-contrast': '#acf7b6',
      },
    },
  },
  'palette.green1': {
    _original: {
      $value: '#aceebb',
      $extensions: {
        mode: {
          light: '#aceebb',
          'light-high-contrast': '#82e596',
          dark: '#7ee787',
          'dark-dimmed': '#8ddb8c',
          'dark-high-contrast': '#72f088',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green1',
    $type: 'color',
    $value: '#aceebb',
    $extensions: {
      mode: {
        light: '#aceebb',
        'light-high-contrast': '#82e596',
        dark: '#7ee787',
        'dark-dimmed': '#8ddb8c',
        'dark-high-contrast': '#72f088',
      },
    },
  },
  'palette.green2': {
    _original: {
      $value: '#6fdd8b',
      $extensions: {
        mode: {
          light: '#6fdd8b',
          'light-high-contrast': '#43c663',
          dark: '#56d364',
          'dark-dimmed': '#6bc46d',
          'dark-high-contrast': '#4ae168',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green2',
    $type: 'color',
    $value: '#6fdd8b',
    $extensions: {
      mode: {
        light: '#6fdd8b',
        'light-high-contrast': '#43c663',
        dark: '#56d364',
        'dark-dimmed': '#6bc46d',
        'dark-high-contrast': '#4ae168',
      },
    },
  },
  'palette.green3': {
    _original: {
      $value: '#4ac26b',
      $extensions: {
        mode: {
          light: '#4ac26b',
          'light-high-contrast': '#26a148',
          dark: '#3fb950',
          'dark-dimmed': '#57ab5a',
          'dark-high-contrast': '#26cd4d',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green3',
    $type: 'color',
    $value: '#4ac26b',
    $extensions: {
      mode: {
        light: '#4ac26b',
        'light-high-contrast': '#26a148',
        dark: '#3fb950',
        'dark-dimmed': '#57ab5a',
        'dark-high-contrast': '#26cd4d',
      },
    },
  },
  'palette.green4': {
    _original: {
      $value: '#2da44e',
      $extensions: {
        mode: {
          light: '#2da44e',
          'light-high-contrast': '#117f32',
          dark: '#2ea043',
          'dark-dimmed': '#46954a',
          'dark-high-contrast': '#09b43a',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green4',
    $type: 'color',
    $value: '#2da44e',
    $extensions: {
      mode: {
        light: '#2da44e',
        'light-high-contrast': '#117f32',
        dark: '#2ea043',
        'dark-dimmed': '#46954a',
        'dark-high-contrast': '#09b43a',
      },
    },
  },
  'palette.green5': {
    _original: {
      $value: '#1a7f37',
      $extensions: {
        mode: {
          light: '#1a7f37',
          'light-high-contrast': '#055d20',
          dark: '#238636',
          'dark-dimmed': '#347d39',
          'dark-high-contrast': '#09b43a',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green5',
    $type: 'color',
    $value: '#1a7f37',
    $extensions: {
      mode: {
        light: '#1a7f37',
        'light-high-contrast': '#055d20',
        dark: '#238636',
        'dark-dimmed': '#347d39',
        'dark-high-contrast': '#09b43a',
      },
    },
  },
  'palette.green6': {
    _original: {
      $value: '#116329',
      $extensions: {
        mode: {
          light: '#116329',
          'light-high-contrast': '#024c1a',
          dark: '#196c2e',
          'dark-dimmed': '#2b6a30',
          'dark-high-contrast': '#02a232',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green6',
    $type: 'color',
    $value: '#116329',
    $extensions: {
      mode: {
        light: '#116329',
        'light-high-contrast': '#024c1a',
        dark: '#196c2e',
        'dark-dimmed': '#2b6a30',
        'dark-high-contrast': '#02a232',
      },
    },
  },
  'palette.green7': {
    _original: {
      $value: '#044f1e',
      $extensions: {
        mode: {
          light: '#044f1e',
          'light-high-contrast': '#013d14',
          dark: '#0f5323',
          'dark-dimmed': '#245829',
          'dark-high-contrast': '#008c2c',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green7',
    $type: 'color',
    $value: '#044f1e',
    $extensions: {
      mode: {
        light: '#044f1e',
        'light-high-contrast': '#013d14',
        dark: '#0f5323',
        'dark-dimmed': '#245829',
        'dark-high-contrast': '#008c2c',
      },
    },
  },
  'palette.green8': {
    _original: {
      $value: '#003d16',
      $extensions: {
        mode: {
          light: '#003d16',
          'light-high-contrast': '#003110',
          dark: '#033a16',
          'dark-dimmed': '#1b4721',
          'dark-high-contrast': '#007728',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green8',
    $type: 'color',
    $value: '#003d16',
    $extensions: {
      mode: {
        light: '#003d16',
        'light-high-contrast': '#003110',
        dark: '#033a16',
        'dark-dimmed': '#1b4721',
        'dark-high-contrast': '#007728',
      },
    },
  },
  'palette.green9': {
    _original: {
      $value: '#002d11',
      $extensions: {
        mode: {
          light: '#002d11',
          'light-high-contrast': '#00230b',
          dark: '#04260f',
          'dark-dimmed': '#113417',
          'dark-high-contrast': '#006222',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.green9',
    $type: 'color',
    $value: '#002d11',
    $extensions: {
      mode: {
        light: '#002d11',
        'light-high-contrast': '#00230b',
        dark: '#04260f',
        'dark-dimmed': '#113417',
        'dark-high-contrast': '#006222',
      },
    },
  },
  'palette.blue0': {
    _original: {
      $value: '#ddf4ff',
      $extensions: {
        mode: {
          light: '#ddf4ff',
          'light-high-contrast': '#dff7ff',
          dark: '#cae8ff',
          'dark-dimmed': '#c6e6ff',
          'dark-high-contrast': '#caeaff',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue0',
    $type: 'color',
    $value: '#ddf4ff',
    $extensions: {
      mode: {
        light: '#ddf4ff',
        'light-high-contrast': '#dff7ff',
        dark: '#cae8ff',
        'dark-dimmed': '#c6e6ff',
        'dark-high-contrast': '#caeaff',
      },
    },
  },
  'palette.blue1': {
    _original: {
      $value: '#b6e3ff',
      $extensions: {
        mode: {
          light: '#b6e3ff',
          'light-high-contrast': '#9cd7ff',
          dark: '#a5d6ff',
          'dark-dimmed': '#96d0ff',
          'dark-high-contrast': '#addcff',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue1',
    $type: 'color',
    $value: '#b6e3ff',
    $extensions: {
      mode: {
        light: '#b6e3ff',
        'light-high-contrast': '#9cd7ff',
        dark: '#a5d6ff',
        'dark-dimmed': '#96d0ff',
        'dark-high-contrast': '#addcff',
      },
    },
  },
  'palette.blue2': {
    _original: {
      $value: '#80ccff',
      $extensions: {
        mode: {
          light: '#80ccff',
          'light-high-contrast': '#67b3fd',
          dark: '#79c0ff',
          'dark-dimmed': '#6cb6ff',
          'dark-high-contrast': '#91cbff',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue2',
    $type: 'color',
    $value: '#80ccff',
    $extensions: {
      mode: {
        light: '#80ccff',
        'light-high-contrast': '#67b3fd',
        dark: '#79c0ff',
        'dark-dimmed': '#6cb6ff',
        'dark-high-contrast': '#91cbff',
      },
    },
  },
  'palette.blue3': {
    _original: {
      $value: '#54aeff',
      $extensions: {
        mode: {
          light: '#54aeff',
          'light-high-contrast': '#368cf9',
          dark: '#58a6ff',
          'dark-dimmed': '#539bf5',
          'dark-high-contrast': '#71b7ff',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue3',
    $type: 'color',
    $value: '#54aeff',
    $extensions: {
      mode: {
        light: '#54aeff',
        'light-high-contrast': '#368cf9',
        dark: '#58a6ff',
        'dark-dimmed': '#539bf5',
        'dark-high-contrast': '#71b7ff',
      },
    },
  },
  'palette.blue4': {
    _original: {
      $value: '#218bff',
      $extensions: {
        mode: {
          light: '#218bff',
          'light-high-contrast': '#1168e3',
          dark: '#388bfd',
          'dark-dimmed': '#4184e4',
          'dark-high-contrast': '#409eff',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue4',
    $type: 'color',
    $value: '#218bff',
    $extensions: {
      mode: {
        light: '#218bff',
        'light-high-contrast': '#1168e3',
        dark: '#388bfd',
        'dark-dimmed': '#4184e4',
        'dark-high-contrast': '#409eff',
      },
    },
  },
  'palette.blue5': {
    _original: {
      $value: '#0969da',
      $extensions: {
        mode: {
          light: '#0969da',
          'light-high-contrast': '#0349b4',
          dark: '#1f6feb',
          'dark-dimmed': '#316dca',
          'dark-high-contrast': '#409eff',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue5',
    $type: 'color',
    $value: '#0969da',
    $extensions: {
      mode: {
        light: '#0969da',
        'light-high-contrast': '#0349b4',
        dark: '#1f6feb',
        'dark-dimmed': '#316dca',
        'dark-high-contrast': '#409eff',
      },
    },
  },
  'palette.blue6': {
    _original: {
      $value: '#0550ae',
      $extensions: {
        mode: {
          light: '#0550ae',
          'light-high-contrast': '#023b95',
          dark: '#1158c7',
          'dark-dimmed': '#255ab2',
          'dark-high-contrast': '#318bf8',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue6',
    $type: 'color',
    $value: '#0550ae',
    $extensions: {
      mode: {
        light: '#0550ae',
        'light-high-contrast': '#023b95',
        dark: '#1158c7',
        'dark-dimmed': '#255ab2',
        'dark-high-contrast': '#318bf8',
      },
    },
  },
  'palette.blue7': {
    _original: {
      $value: '#033d8b',
      $extensions: {
        mode: {
          light: '#033d8b',
          'light-high-contrast': '#022f7a',
          dark: '#0d419d',
          'dark-dimmed': '#1b4b91',
          'dark-high-contrast': '#2672f3',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue7',
    $type: 'color',
    $value: '#033d8b',
    $extensions: {
      mode: {
        light: '#033d8b',
        'light-high-contrast': '#022f7a',
        dark: '#0d419d',
        'dark-dimmed': '#1b4b91',
        'dark-high-contrast': '#2672f3',
      },
    },
  },
  'palette.blue8': {
    _original: {
      $value: '#0a3069',
      $extensions: {
        mode: {
          light: '#0a3069',
          'light-high-contrast': '#032563',
          dark: '#0c2d6b',
          'dark-dimmed': '#143d79',
          'dark-high-contrast': '#1e60d5',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue8',
    $type: 'color',
    $value: '#0a3069',
    $extensions: {
      mode: {
        light: '#0a3069',
        'light-high-contrast': '#032563',
        dark: '#0c2d6b',
        'dark-dimmed': '#143d79',
        'dark-high-contrast': '#1e60d5',
      },
    },
  },
  'palette.blue9': {
    _original: {
      $value: '#002155',
      $extensions: {
        mode: {
          light: '#002155',
          'light-high-contrast': '#021a4a',
          dark: '#051d4d',
          'dark-dimmed': '#0f2d5c',
          'dark-high-contrast': '#194fb1',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.blue9',
    $type: 'color',
    $value: '#002155',
    $extensions: {
      mode: {
        light: '#002155',
        'light-high-contrast': '#021a4a',
        dark: '#051d4d',
        'dark-dimmed': '#0f2d5c',
        'dark-high-contrast': '#194fb1',
      },
    },
  },
  'palette.coral0': {
    _original: {
      $value: '#FFF0EB',
      $extensions: {
        mode: {
          light: '#FFF0EB',
          'light-high-contrast': '#fff0ed',
          dark: '#FFDDD2',
          'dark-dimmed': '#FFDACF',
          'dark-high-contrast': '#FFDED4',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral0',
    $type: 'color',
    $value: '#fff0eb',
    $extensions: {
      mode: {
        light: '#fff0eb',
        'light-high-contrast': '#fff0ed',
        dark: '#ffddd2',
        'dark-dimmed': '#ffdacf',
        'dark-high-contrast': '#ffded4',
      },
    },
  },
  'palette.coral1': {
    _original: {
      $value: '#FFD6CC',
      $extensions: {
        mode: {
          light: '#FFD6CC',
          'light-high-contrast': '#ffc2b6',
          dark: '#FFC2B2',
          'dark-dimmed': '#FFB9A5',
          'dark-high-contrast': '#FFCBB9',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral1',
    $type: 'color',
    $value: '#ffd6cc',
    $extensions: {
      mode: {
        light: '#ffd6cc',
        'light-high-contrast': '#ffc2b6',
        dark: '#ffc2b2',
        'dark-dimmed': '#ffb9a5',
        'dark-high-contrast': '#ffcbb9',
      },
    },
  },
  'palette.coral2': {
    _original: {
      $value: '#FFB4A1',
      $extensions: {
        mode: {
          light: '#FFB4A1',
          'light-high-contrast': '#ff8f7e',
          dark: '#FFA28B',
          'dark-dimmed': '#F79981',
          'dark-high-contrast': '#FFB39B',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral2',
    $type: 'color',
    $value: '#ffb4a1',
    $extensions: {
      mode: {
        light: '#ffb4a1',
        'light-high-contrast': '#ff8f7e',
        dark: '#ffa28b',
        'dark-dimmed': '#f79981',
        'dark-high-contrast': '#ffb39b',
      },
    },
  },
  'palette.coral3': {
    _original: {
      $value: '#FD8C73',
      $extensions: {
        mode: {
          light: '#FD8C73',
          'light-high-contrast': '#ef5b48',
          dark: '#F78166',
          'dark-dimmed': '#EC775C',
          'dark-high-contrast': '#FF967D',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral3',
    $type: 'color',
    $value: '#fd8c73',
    $extensions: {
      mode: {
        light: '#fd8c73',
        'light-high-contrast': '#ef5b48',
        dark: '#f78166',
        'dark-dimmed': '#ec775c',
        'dark-high-contrast': '#ff967d',
      },
    },
  },
  'palette.coral4': {
    _original: {
      $value: '#EC6547',
      $extensions: {
        mode: {
          light: '#EC6547',
          'light-high-contrast': '#cd3425',
          dark: '#EA6045',
          'dark-dimmed': '#DE5B41',
          'dark-high-contrast': '#FC704F',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral4',
    $type: 'color',
    $value: '#ec6547',
    $extensions: {
      mode: {
        light: '#ec6547',
        'light-high-contrast': '#cd3425',
        dark: '#ea6045',
        'dark-dimmed': '#de5b41',
        'dark-high-contrast': '#fc704f',
      },
    },
  },
  'palette.coral5': {
    _original: {
      $value: '#C4432B',
      $extensions: {
        mode: {
          light: '#C4432B',
          'light-high-contrast': '#9f1710',
          dark: '#CF462D',
          'dark-dimmed': '#C2442D',
          'dark-high-contrast': '#FC704F',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral5',
    $type: 'color',
    $value: '#c4432b',
    $extensions: {
      mode: {
        light: '#c4432b',
        'light-high-contrast': '#9f1710',
        dark: '#cf462d',
        'dark-dimmed': '#c2442d',
        'dark-high-contrast': '#fc704f',
      },
    },
  },
  'palette.coral6': {
    _original: {
      $value: '#9E2F1C',
      $extensions: {
        mode: {
          light: '#9E2F1C',
          'light-high-contrast': '#870706',
          dark: '#AC3220',
          'dark-dimmed': '#A93524',
          'dark-high-contrast': '#F75133',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral6',
    $type: 'color',
    $value: '#9e2f1c',
    $extensions: {
      mode: {
        light: '#9e2f1c',
        'light-high-contrast': '#870706',
        dark: '#ac3220',
        'dark-dimmed': '#a93524',
        'dark-high-contrast': '#f75133',
      },
    },
  },
  'palette.coral7': {
    _original: {
      $value: '#801F0F',
      $extensions: {
        mode: {
          light: '#801F0F',
          'light-high-contrast': '#6f0107',
          dark: '#872012',
          'dark-dimmed': '#8D291B',
          'dark-high-contrast': '#E03B21',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral7',
    $type: 'color',
    $value: '#801f0f',
    $extensions: {
      mode: {
        light: '#801f0f',
        'light-high-contrast': '#6f0107',
        dark: '#872012',
        'dark-dimmed': '#8d291b',
        'dark-high-contrast': '#e03b21',
      },
    },
  },
  'palette.coral8': {
    _original: {
      $value: '#691105',
      $extensions: {
        mode: {
          light: '#691105',
          'light-high-contrast': '#5b0002',
          dark: '#640D04',
          'dark-dimmed': '#771D13',
          'dark-high-contrast': '#C62612',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral8',
    $type: 'color',
    $value: '#691105',
    $extensions: {
      mode: {
        light: '#691105',
        'light-high-contrast': '#5b0002',
        dark: '#640d04',
        'dark-dimmed': '#771d13',
        'dark-high-contrast': '#c62612',
      },
    },
  },
  'palette.coral9': {
    _original: {
      $value: '#510901',
      $extensions: {
        mode: {
          light: '#510901',
          'light-high-contrast': '#430200',
          dark: '#460701',
          'dark-dimmed': '#5D1008',
          'dark-high-contrast': '#A91500',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.coral9',
    $type: 'color',
    $value: '#510901',
    $extensions: {
      mode: {
        light: '#510901',
        'light-high-contrast': '#430200',
        dark: '#460701',
        'dark-dimmed': '#5d1008',
        'dark-high-contrast': '#a91500',
      },
    },
  },
  'palette.red0': {
    _original: {
      $value: '#FFEBE9',
      $extensions: {
        mode: {
          light: '#FFEBE9',
          'light-high-contrast': '#fff0ee',
          dark: '#ffdcd7',
          'dark-dimmed': '#ffd8d3',
          'dark-high-contrast': '#ffdedb',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red0',
    $type: 'color',
    $value: '#ffebe9',
    $extensions: {
      mode: {
        light: '#ffebe9',
        'light-high-contrast': '#fff0ee',
        dark: '#ffdcd7',
        'dark-dimmed': '#ffd8d3',
        'dark-high-contrast': '#ffdedb',
      },
    },
  },
  'palette.red1': {
    _original: {
      $value: '#ffcecb',
      $extensions: {
        mode: {
          light: '#ffcecb',
          'light-high-contrast': '#ffc1bc',
          dark: '#ffc1ba',
          'dark-dimmed': '#ffb8b0',
          'dark-high-contrast': '#ffc9c7',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red1',
    $type: 'color',
    $value: '#ffcecb',
    $extensions: {
      mode: {
        light: '#ffcecb',
        'light-high-contrast': '#ffc1bc',
        dark: '#ffc1ba',
        'dark-dimmed': '#ffb8b0',
        'dark-high-contrast': '#ffc9c7',
      },
    },
  },
  'palette.red2': {
    _original: {
      $value: '#ffaba8',
      $extensions: {
        mode: {
          light: '#ffaba8',
          'light-high-contrast': '#ff8e8a',
          dark: '#ffa198',
          'dark-dimmed': '#ff938a',
          'dark-high-contrast': '#ffb1af',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red2',
    $type: 'color',
    $value: '#ffaba8',
    $extensions: {
      mode: {
        light: '#ffaba8',
        'light-high-contrast': '#ff8e8a',
        dark: '#ffa198',
        'dark-dimmed': '#ff938a',
        'dark-high-contrast': '#ffb1af',
      },
    },
  },
  'palette.red3': {
    _original: {
      $value: '#ff8182',
      $extensions: {
        mode: {
          light: '#ff8182',
          'light-high-contrast': '#ee5a5d',
          dark: '#ff7b72',
          'dark-dimmed': '#f47067',
          'dark-high-contrast': '#ff9492',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red3',
    $type: 'color',
    $value: '#ff8182',
    $extensions: {
      mode: {
        light: '#ff8182',
        'light-high-contrast': '#ee5a5d',
        dark: '#ff7b72',
        'dark-dimmed': '#f47067',
        'dark-high-contrast': '#ff9492',
      },
    },
  },
  'palette.red4': {
    _original: {
      $value: '#fa4549',
      $extensions: {
        mode: {
          light: '#fa4549',
          'light-high-contrast': '#d5232c',
          dark: '#f85149',
          'dark-dimmed': '#e5534b',
          'dark-high-contrast': '#ff6a69',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red4',
    $type: 'color',
    $value: '#fa4549',
    $extensions: {
      mode: {
        light: '#fa4549',
        'light-high-contrast': '#d5232c',
        dark: '#f85149',
        'dark-dimmed': '#e5534b',
        'dark-high-contrast': '#ff6a69',
      },
    },
  },
  'palette.red5': {
    _original: {
      $value: '#cf222e',
      $extensions: {
        mode: {
          light: '#cf222e',
          'light-high-contrast': '#a0111f',
          dark: '#da3633',
          'dark-dimmed': '#c93c37',
          'dark-high-contrast': '#ff6a69',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red5',
    $type: 'color',
    $value: '#cf222e',
    $extensions: {
      mode: {
        light: '#cf222e',
        'light-high-contrast': '#a0111f',
        dark: '#da3633',
        'dark-dimmed': '#c93c37',
        'dark-high-contrast': '#ff6a69',
      },
    },
  },
  'palette.red6': {
    _original: {
      $value: '#a40e26',
      $extensions: {
        mode: {
          light: '#a40e26',
          'light-high-contrast': '#86061d',
          dark: '#b62324',
          'dark-dimmed': '#ad2e2c',
          'dark-high-contrast': '#ff4445',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red6',
    $type: 'color',
    $value: '#a40e26',
    $extensions: {
      mode: {
        light: '#a40e26',
        'light-high-contrast': '#86061d',
        dark: '#b62324',
        'dark-dimmed': '#ad2e2c',
        'dark-high-contrast': '#ff4445',
      },
    },
  },
  'palette.red7': {
    _original: {
      $value: '#82071e',
      $extensions: {
        mode: {
          light: '#82071e',
          'light-high-contrast': '#6e011a',
          dark: '#8e1519',
          'dark-dimmed': '#922323',
          'dark-high-contrast': '#e82a2f',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red7',
    $type: 'color',
    $value: '#82071e',
    $extensions: {
      mode: {
        light: '#82071e',
        'light-high-contrast': '#6e011a',
        dark: '#8e1519',
        'dark-dimmed': '#922323',
        'dark-high-contrast': '#e82a2f',
      },
    },
  },
  'palette.red8': {
    _original: {
      $value: '#660018',
      $extensions: {
        mode: {
          light: '#660018',
          'light-high-contrast': '#5a0016',
          dark: '#67060c',
          'dark-dimmed': '#78191b',
          'dark-high-contrast': '#cc1421',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red8',
    $type: 'color',
    $value: '#660018',
    $extensions: {
      mode: {
        light: '#660018',
        'light-high-contrast': '#5a0016',
        dark: '#67060c',
        'dark-dimmed': '#78191b',
        'dark-high-contrast': '#cc1421',
      },
    },
  },
  'palette.red9': {
    _original: {
      $value: '#4c0014',
      $extensions: {
        mode: {
          light: '#4c0014',
          'light-high-contrast': '#430011',
          dark: '#490202',
          'dark-dimmed': '#5D0F12',
          'dark-high-contrast': '#ad0116',
        },
      },
    },
    _group: {
      id: 'palette',
      $extensions: {
        requiredModes: [],
        modes: [
          'light',
          'light-high-contrast',
          'dark',
          'dark-dimmed',
          'dark-high-contrast',
        ],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'palette.red9',
    $type: 'color',
    $value: '#4c0014',
    $extensions: {
      mode: {
        light: '#4c0014',
        'light-high-contrast': '#430011',
        dark: '#490202',
        'dark-dimmed': '#5d0f12',
        'dark-high-contrast': '#ad0116',
      },
    },
  },
  'color.background': {
    _original: {
      $value: '{palette.gray0}',
    },
    _group: {
      id: 'color',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'color.background',
    $type: 'color',
    $value: '#f2f4f8',
  },
  'color.text.error': {
    _original: {
      $value: '{palette.red7}',
    },
    _group: {
      id: 'color.text',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'color.text.error',
    $type: 'color',
    $value: '#82071e',
  },
  'color.text.link': {
    _original: {
      $value: '{palette.blue5}',
    },
    _group: {
      id: 'color.text',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'color',
    },
    id: 'color.text.link',
    $type: 'color',
    $value: '#0969da',
  },
  'spacing.spacer0': {
    _original: {
      $value: '0px',
    },
    _group: {
      id: 'spacing',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'spacing.spacer0',
    $type: 'dimension',
    $value: '0',
  },
  'spacing.spacerXs': {
    _original: {
      $value: '4px',
    },
    _group: {
      id: 'spacing',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'spacing.spacerXs',
    $type: 'dimension',
    $value: '4px',
  },
  'spacing.spacerS': {
    _original: {
      $value: '8px',
    },
    _group: {
      id: 'spacing',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'spacing.spacerS',
    $type: 'dimension',
    $value: '8px',
  },
  'spacing.spacerM': {
    _original: {
      $value: '16px',
    },
    _group: {
      id: 'spacing',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'spacing.spacerM',
    $type: 'dimension',
    $value: '16px',
  },
  'spacing.spacerX': {
    _original: {
      $value: '24px',
    },
    _group: {
      id: 'spacing',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'spacing.spacerX',
    $type: 'dimension',
    $value: '24px',
  },
  'spacing.spacerXl': {
    _original: {
      $value: '32px',
    },
    _group: {
      id: 'spacing',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'spacing.spacerXl',
    $type: 'dimension',
    $value: '32px',
  },
  'spacing.spacerXxl': {
    _original: {
      $value: '40px',
    },
    _group: {
      id: 'spacing',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'spacing.spacerXxl',
    $type: 'dimension',
    $value: '40px',
  },
  'font.family.system': {
    _original: {
      $value: [
        '-apple-system,',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Helvetica',
        'Arial',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
      ],
    },
    _group: {
      id: 'font.family',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'font',
    },
    id: 'font.family.system',
    $type: 'font',
    $value: [
      '-apple-system,',
      'BlinkMacSystemFont',
      'Segoe UI',
      'Helvetica',
      'Arial',
      'sans-serif',
      'Apple Color Emoji',
      'Segoe UI Emoji',
    ],
  },
  'font.family.monospace': {
    _original: {
      $value: [
        'SFMono-Regular',
        'Consolas',
        'Liberation Mono',
        'Menlo',
        'Courier',
        'monospace',
      ],
    },
    _group: {
      id: 'font.family',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'font',
    },
    id: 'font.family.monospace',
    $type: 'font',
    $value: [
      'SFMono-Regular',
      'Consolas',
      'Liberation Mono',
      'Menlo',
      'Courier',
      'monospace',
    ],
  },
  'font.family.display': {
    _original: {
      $value: [
        'InterUI',
        '-apple-system',
        'BlinkMacSystemFont',
        'Helvetica Neue',
        'Segoe UI',
        'Oxygen',
        'Ubuntu',
        'Cantarell',
        'Open Sans',
        'sans-serif',
      ],
    },
    _group: {
      id: 'font.family',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'font',
    },
    id: 'font.family.display',
    $type: 'font',
    $value: [
      'InterUI',
      '-apple-system',
      'BlinkMacSystemFont',
      'Helvetica Neue',
      'Segoe UI',
      'Oxygen',
      'Ubuntu',
      'Cantarell',
      'Open Sans',
      'sans-serif',
    ],
  },
  'font.family.size.f00': {
    _original: {
      $value: '32px',
      $extensions: {
        mode: {
          mobile: '32px',
          desktop: '48px',
        },
      },
    },
    _group: {
      id: 'font.family.size',
      $extensions: {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.size.f00',
    $type: 'dimension',
    $value: '32px',
    $extensions: {
      mode: {
        mobile: '32px',
        desktop: '48px',
      },
    },
  },
  'font.family.size.f0': {
    _original: {
      $value: '32px',
      $extensions: {
        mode: {
          mobile: '32px',
          desktop: '40px',
        },
      },
    },
    _group: {
      id: 'font.family.size',
      $extensions: {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.size.f0',
    $type: 'dimension',
    $value: '32px',
    $extensions: {
      mode: {
        mobile: '32px',
        desktop: '40px',
      },
    },
  },
  'font.family.size.f1': {
    _original: {
      $value: '26px',
      $extensions: {
        mode: {
          mobile: '26px',
          desktop: '32px',
        },
      },
    },
    _group: {
      id: 'font.family.size',
      $extensions: {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.size.f1',
    $type: 'dimension',
    $value: '26px',
    $extensions: {
      mode: {
        mobile: '26px',
        desktop: '32px',
      },
    },
  },
  'font.family.size.f2': {
    _original: {
      $value: '22px',
      $extensions: {
        mode: {
          mobile: '22px',
          desktop: '24px',
        },
      },
    },
    _group: {
      id: 'font.family.size',
      $extensions: {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.size.f2',
    $type: 'dimension',
    $value: '22px',
    $extensions: {
      mode: {
        mobile: '22px',
        desktop: '24px',
      },
    },
  },
  'font.family.size.f3': {
    _original: {
      $value: '16px',
      $extensions: {
        mode: {
          mobile: '16px',
          desktop: '20px',
        },
      },
    },
    _group: {
      id: 'font.family.size',
      $extensions: {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.size.f3',
    $type: 'dimension',
    $value: '16px',
    $extensions: {
      mode: {
        mobile: '16px',
        desktop: '20px',
      },
    },
  },
  'font.family.size.f4': {
    _original: {
      $value: '16px',
      $extensions: {
        mode: {
          mobile: '16px',
          desktop: '16px',
        },
      },
    },
    _group: {
      id: 'font.family.size',
      $extensions: {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.size.f4',
    $type: 'dimension',
    $value: '16px',
    $extensions: {
      mode: {
        mobile: '16px',
        desktop: '16px',
      },
    },
  },
  'font.family.size.f5': {
    _original: {
      $value: '14px',
      $extensions: {
        mode: {
          mobile: '14px',
          desktop: '14px',
        },
      },
    },
    _group: {
      id: 'font.family.size',
      $extensions: {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.size.f5',
    $type: 'dimension',
    $value: '14px',
    $extensions: {
      mode: {
        mobile: '14px',
        desktop: '14px',
      },
    },
  },
  'font.family.size.f6': {
    _original: {
      $value: '12px',
      $extensions: {
        mode: {
          mobile: '12px',
          desktop: '12px',
        },
      },
    },
    _group: {
      id: 'font.family.size',
      $extensions: {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.size.f6',
    $type: 'dimension',
    $value: '12px',
    $extensions: {
      mode: {
        mobile: '12px',
        desktop: '12px',
      },
    },
  },
  'font.family.lineHeight.default': {
    _original: {
      $value: '1.5',
    },
    _group: {
      id: 'font.family.lineHeight',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.lineHeight.default',
    $type: 'dimension',
    $value: '1.5',
  },
  'font.family.lineHeight.condensed': {
    _original: {
      $value: '1.25',
    },
    _group: {
      id: 'font.family.lineHeight',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.lineHeight.condensed',
    $type: 'dimension',
    $value: '1.25',
  },
  'font.family.lineHeight.condensedUltra': {
    _original: {
      $value: '1',
    },
    _group: {
      id: 'font.family.lineHeight',
      $extensions: {
        requiredModes: [],
      },
      $name: 'NosEditor themes',
      $description: 'design tokens for noseditor',
      $type: 'dimension',
    },
    id: 'font.family.lineHeight.condensedUltra',
    $type: 'dimension',
    $value: '1',
  },
};

export const modes = {
  'palette.black': {
    light: '#1b1f24',
    'light-high-contrast': '#010409',
    dark: '#010409',
    white: '#f0f6fc',
    'dark-dimmed': '#1c2128',
    'dark-high-contrast': '#010409',
  },
  'palette.white': {
    light: '#ffffff',
    'light-high-contrast': '#ffffff',
    dark: '#f0f6fc',
    'dark-dimmed': '#cdd9e5',
    'dark-high-contrast': '#ffffff',
  },
  'palette.gray0': {
    light: '#f2f4f8',
    'light-high-contrast': '#ffffff',
    dark: '#f0f6fc',
    'dark-dimmed': '#cdd9e5',
    'dark-high-contrast': '#ffffff',
  },
  'palette.gray1': {
    light: '#eceff4',
    'light-high-contrast': '#e7ecf0',
    dark: '#c9d1d9',
    'dark-dimmed': '#adbac7',
    'dark-high-contrast': '#f0f3f6',
  },
  'palette.gray2': {
    light: '#e5e9f0',
    'light-high-contrast': '#ced5dc',
    dark: '#b1bac4',
    'dark-dimmed': '#909dab',
    'dark-high-contrast': '#d9dee3',
  },
  'palette.gray3': {
    light: '#e5e9f0',
    'light-high-contrast': '#acb6c0',
    dark: '#8b949e',
    'dark-dimmed': '#768390',
    'dark-high-contrast': '#bdc4cc',
  },
  'palette.gray4': {
    light: '#afb8c1',
    'light-high-contrast': '#88929d',
    dark: '#6e7681',
    'dark-dimmed': '#636e7b',
    'dark-high-contrast': '#9ea7b3',
  },
  'palette.gray5': {
    light: '#6e7781',
    'light-high-contrast': '#66707b',
    dark: '#484f58',
    'dark-dimmed': '#545d68',
    'dark-high-contrast': '#7a828e',
  },
  'palette.gray6': {
    light: '#4c566a',
    'light-high-contrast': '#4b535d',
    dark: '#30363d',
    'dark-dimmed': '#444c56',
    'dark-high-contrast': '#525964',
  },
  'palette.gray7': {
    light: '#434c5e',
    'light-high-contrast': '#343b43',
    dark: '#21262d',
    'dark-dimmed': '#373e47',
    'dark-high-contrast': '#272b33',
  },
  'palette.gray8': {
    light: '#434c5e',
    'light-high-contrast': '#20252c',
    dark: '#161b22',
    'dark-dimmed': '#2d333b',
    'dark-high-contrast': '#272b33',
  },
  'palette.gray9': {
    light: '#2e3440',
    'light-high-contrast': '#0e1116',
    dark: '#0d1117',
    'dark-dimmed': '#22272e',
    'dark-high-contrast': '#0a0c10',
  },
  'palette.green0': {
    light: '#dafbe1',
    'light-high-contrast': '#d2fedb',
    dark: '#aff5b4',
    'dark-dimmed': '#b4f1b4',
    'dark-high-contrast': '#acf7b6',
  },
  'palette.green1': {
    light: '#aceebb',
    'light-high-contrast': '#82e596',
    dark: '#7ee787',
    'dark-dimmed': '#8ddb8c',
    'dark-high-contrast': '#72f088',
  },
  'palette.green2': {
    light: '#6fdd8b',
    'light-high-contrast': '#43c663',
    dark: '#56d364',
    'dark-dimmed': '#6bc46d',
    'dark-high-contrast': '#4ae168',
  },
  'palette.green3': {
    light: '#4ac26b',
    'light-high-contrast': '#26a148',
    dark: '#3fb950',
    'dark-dimmed': '#57ab5a',
    'dark-high-contrast': '#26cd4d',
  },
  'palette.green4': {
    light: '#2da44e',
    'light-high-contrast': '#117f32',
    dark: '#2ea043',
    'dark-dimmed': '#46954a',
    'dark-high-contrast': '#09b43a',
  },
  'palette.green5': {
    light: '#1a7f37',
    'light-high-contrast': '#055d20',
    dark: '#238636',
    'dark-dimmed': '#347d39',
    'dark-high-contrast': '#09b43a',
  },
  'palette.green6': {
    light: '#116329',
    'light-high-contrast': '#024c1a',
    dark: '#196c2e',
    'dark-dimmed': '#2b6a30',
    'dark-high-contrast': '#02a232',
  },
  'palette.green7': {
    light: '#044f1e',
    'light-high-contrast': '#013d14',
    dark: '#0f5323',
    'dark-dimmed': '#245829',
    'dark-high-contrast': '#008c2c',
  },
  'palette.green8': {
    light: '#003d16',
    'light-high-contrast': '#003110',
    dark: '#033a16',
    'dark-dimmed': '#1b4721',
    'dark-high-contrast': '#007728',
  },
  'palette.green9': {
    light: '#002d11',
    'light-high-contrast': '#00230b',
    dark: '#04260f',
    'dark-dimmed': '#113417',
    'dark-high-contrast': '#006222',
  },
  'palette.blue0': {
    light: '#ddf4ff',
    'light-high-contrast': '#dff7ff',
    dark: '#cae8ff',
    'dark-dimmed': '#c6e6ff',
    'dark-high-contrast': '#caeaff',
  },
  'palette.blue1': {
    light: '#b6e3ff',
    'light-high-contrast': '#9cd7ff',
    dark: '#a5d6ff',
    'dark-dimmed': '#96d0ff',
    'dark-high-contrast': '#addcff',
  },
  'palette.blue2': {
    light: '#80ccff',
    'light-high-contrast': '#67b3fd',
    dark: '#79c0ff',
    'dark-dimmed': '#6cb6ff',
    'dark-high-contrast': '#91cbff',
  },
  'palette.blue3': {
    light: '#54aeff',
    'light-high-contrast': '#368cf9',
    dark: '#58a6ff',
    'dark-dimmed': '#539bf5',
    'dark-high-contrast': '#71b7ff',
  },
  'palette.blue4': {
    light: '#218bff',
    'light-high-contrast': '#1168e3',
    dark: '#388bfd',
    'dark-dimmed': '#4184e4',
    'dark-high-contrast': '#409eff',
  },
  'palette.blue5': {
    light: '#0969da',
    'light-high-contrast': '#0349b4',
    dark: '#1f6feb',
    'dark-dimmed': '#316dca',
    'dark-high-contrast': '#409eff',
  },
  'palette.blue6': {
    light: '#0550ae',
    'light-high-contrast': '#023b95',
    dark: '#1158c7',
    'dark-dimmed': '#255ab2',
    'dark-high-contrast': '#318bf8',
  },
  'palette.blue7': {
    light: '#033d8b',
    'light-high-contrast': '#022f7a',
    dark: '#0d419d',
    'dark-dimmed': '#1b4b91',
    'dark-high-contrast': '#2672f3',
  },
  'palette.blue8': {
    light: '#0a3069',
    'light-high-contrast': '#032563',
    dark: '#0c2d6b',
    'dark-dimmed': '#143d79',
    'dark-high-contrast': '#1e60d5',
  },
  'palette.blue9': {
    light: '#002155',
    'light-high-contrast': '#021a4a',
    dark: '#051d4d',
    'dark-dimmed': '#0f2d5c',
    'dark-high-contrast': '#194fb1',
  },
  'palette.coral0': {
    light: '#fff0eb',
    'light-high-contrast': '#fff0ed',
    dark: '#ffddd2',
    'dark-dimmed': '#ffdacf',
    'dark-high-contrast': '#ffded4',
  },
  'palette.coral1': {
    light: '#ffd6cc',
    'light-high-contrast': '#ffc2b6',
    dark: '#ffc2b2',
    'dark-dimmed': '#ffb9a5',
    'dark-high-contrast': '#ffcbb9',
  },
  'palette.coral2': {
    light: '#ffb4a1',
    'light-high-contrast': '#ff8f7e',
    dark: '#ffa28b',
    'dark-dimmed': '#f79981',
    'dark-high-contrast': '#ffb39b',
  },
  'palette.coral3': {
    light: '#fd8c73',
    'light-high-contrast': '#ef5b48',
    dark: '#f78166',
    'dark-dimmed': '#ec775c',
    'dark-high-contrast': '#ff967d',
  },
  'palette.coral4': {
    light: '#ec6547',
    'light-high-contrast': '#cd3425',
    dark: '#ea6045',
    'dark-dimmed': '#de5b41',
    'dark-high-contrast': '#fc704f',
  },
  'palette.coral5': {
    light: '#c4432b',
    'light-high-contrast': '#9f1710',
    dark: '#cf462d',
    'dark-dimmed': '#c2442d',
    'dark-high-contrast': '#fc704f',
  },
  'palette.coral6': {
    light: '#9e2f1c',
    'light-high-contrast': '#870706',
    dark: '#ac3220',
    'dark-dimmed': '#a93524',
    'dark-high-contrast': '#f75133',
  },
  'palette.coral7': {
    light: '#801f0f',
    'light-high-contrast': '#6f0107',
    dark: '#872012',
    'dark-dimmed': '#8d291b',
    'dark-high-contrast': '#e03b21',
  },
  'palette.coral8': {
    light: '#691105',
    'light-high-contrast': '#5b0002',
    dark: '#640d04',
    'dark-dimmed': '#771d13',
    'dark-high-contrast': '#c62612',
  },
  'palette.coral9': {
    light: '#510901',
    'light-high-contrast': '#430200',
    dark: '#460701',
    'dark-dimmed': '#5d1008',
    'dark-high-contrast': '#a91500',
  },
  'palette.red0': {
    light: '#ffebe9',
    'light-high-contrast': '#fff0ee',
    dark: '#ffdcd7',
    'dark-dimmed': '#ffd8d3',
    'dark-high-contrast': '#ffdedb',
  },
  'palette.red1': {
    light: '#ffcecb',
    'light-high-contrast': '#ffc1bc',
    dark: '#ffc1ba',
    'dark-dimmed': '#ffb8b0',
    'dark-high-contrast': '#ffc9c7',
  },
  'palette.red2': {
    light: '#ffaba8',
    'light-high-contrast': '#ff8e8a',
    dark: '#ffa198',
    'dark-dimmed': '#ff938a',
    'dark-high-contrast': '#ffb1af',
  },
  'palette.red3': {
    light: '#ff8182',
    'light-high-contrast': '#ee5a5d',
    dark: '#ff7b72',
    'dark-dimmed': '#f47067',
    'dark-high-contrast': '#ff9492',
  },
  'palette.red4': {
    light: '#fa4549',
    'light-high-contrast': '#d5232c',
    dark: '#f85149',
    'dark-dimmed': '#e5534b',
    'dark-high-contrast': '#ff6a69',
  },
  'palette.red5': {
    light: '#cf222e',
    'light-high-contrast': '#a0111f',
    dark: '#da3633',
    'dark-dimmed': '#c93c37',
    'dark-high-contrast': '#ff6a69',
  },
  'palette.red6': {
    light: '#a40e26',
    'light-high-contrast': '#86061d',
    dark: '#b62324',
    'dark-dimmed': '#ad2e2c',
    'dark-high-contrast': '#ff4445',
  },
  'palette.red7': {
    light: '#82071e',
    'light-high-contrast': '#6e011a',
    dark: '#8e1519',
    'dark-dimmed': '#922323',
    'dark-high-contrast': '#e82a2f',
  },
  'palette.red8': {
    light: '#660018',
    'light-high-contrast': '#5a0016',
    dark: '#67060c',
    'dark-dimmed': '#78191b',
    'dark-high-contrast': '#cc1421',
  },
  'palette.red9': {
    light: '#4c0014',
    'light-high-contrast': '#430011',
    dark: '#490202',
    'dark-dimmed': '#5d0f12',
    'dark-high-contrast': '#ad0116',
  },
  'font.family.size.f00': {
    mobile: '32px',
    desktop: '48px',
  },
  'font.family.size.f0': {
    mobile: '32px',
    desktop: '40px',
  },
  'font.family.size.f1': {
    mobile: '26px',
    desktop: '32px',
  },
  'font.family.size.f2': {
    mobile: '22px',
    desktop: '24px',
  },
  'font.family.size.f3': {
    mobile: '16px',
    desktop: '20px',
  },
  'font.family.size.f4': {
    mobile: '16px',
    desktop: '16px',
  },
  'font.family.size.f5': {
    mobile: '14px',
    desktop: '14px',
  },
  'font.family.size.f6': {
    mobile: '12px',
    desktop: '12px',
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID])
    return modes[tokenID][modeName];
  return tokens[tokenID];
}
