
/**
 * Design Tokens
 * Autogenerated from npm run build:design-tokens.
 * use with same-name.css.
 * DO NOT EDIT!
 */
export const themed = {
  palette: {
    black: 'var(--nos-palette-black)',
    white: 'var(--nos-palette-white)',
    gray25: 'var(--nos-palette-gray25)',
    gray50: 'var(--nos-palette-gray50)',
    gray100: 'var(--nos-palette-gray100)',
    gray200: 'var(--nos-palette-gray200)',
    gray300: 'var(--nos-palette-gray300)',
    gray400: 'var(--nos-palette-gray400)',
    gray500: 'var(--nos-palette-gray500)',
    gray600: 'var(--nos-palette-gray600)',
    gray700: 'var(--nos-palette-gray700)',
    gray800: 'var(--nos-palette-gray800)',
    gray900: 'var(--nos-palette-gray900)',
    grey50: 'var(--nos-palette-grey50)',
    grey100: 'var(--nos-palette-grey100)',
    grey200: 'var(--nos-palette-grey200)',
    grey300: 'var(--nos-palette-grey300)',
    grey400: 'var(--nos-palette-grey400)',
    grey500: 'var(--nos-palette-grey500)',
    grey600: 'var(--nos-palette-grey600)',
    grey700: 'var(--nos-palette-grey700)',
    grey800: 'var(--nos-palette-grey800)',
    grey900: 'var(--nos-palette-grey900)',
    teal50: 'var(--nos-palette-teal50)',
    teal100: 'var(--nos-palette-teal100)',
    teal200: 'var(--nos-palette-teal200)',
    teal300: 'var(--nos-palette-teal300)',
    teal400: 'var(--nos-palette-teal400)',
    teal500: 'var(--nos-palette-teal500)',
    teal600: 'var(--nos-palette-teal600)',
    teal700: 'var(--nos-palette-teal700)',
    teal800: 'var(--nos-palette-teal800)',
    teal900: 'var(--nos-palette-teal900)',
    green50: 'var(--nos-palette-green50)',
    green100: 'var(--nos-palette-green100)',
    green200: 'var(--nos-palette-green200)',
    green300: 'var(--nos-palette-green300)',
    green400: 'var(--nos-palette-green400)',
    green500: 'var(--nos-palette-green500)',
    green600: 'var(--nos-palette-green600)',
    green700: 'var(--nos-palette-green700)',
    green800: 'var(--nos-palette-green800)',
    green900: 'var(--nos-palette-green900)',
    blue50: 'var(--nos-palette-blue50)',
    blue100: 'var(--nos-palette-blue100)',
    blue200: 'var(--nos-palette-blue200)',
    blue300: 'var(--nos-palette-blue300)',
    blue400: 'var(--nos-palette-blue400)',
    blue500: 'var(--nos-palette-blue500)',
    blue600: 'var(--nos-palette-blue600)',
    blue700: 'var(--nos-palette-blue700)',
    blue800: 'var(--nos-palette-blue800)',
    blue900: 'var(--nos-palette-blue900)',
    orange50: 'var(--nos-palette-orange50)',
    orange100: 'var(--nos-palette-orange100)',
    orange200: 'var(--nos-palette-orange200)',
    orange300: 'var(--nos-palette-orange300)',
    orange400: 'var(--nos-palette-orange400)',
    orange500: 'var(--nos-palette-orange500)',
    orange600: 'var(--nos-palette-orange600)',
    orange700: 'var(--nos-palette-orange700)',
    orange800: 'var(--nos-palette-orange800)',
    orange900: 'var(--nos-palette-orange900)',
    red50: 'var(--nos-palette-red50)',
    red100: 'var(--nos-palette-red100)',
    red200: 'var(--nos-palette-red200)',
    red300: 'var(--nos-palette-red300)',
    red400: 'var(--nos-palette-red400)',
    red500: 'var(--nos-palette-red500)',
    red600: 'var(--nos-palette-red600)',
    red700: 'var(--nos-palette-red700)',
    red800: 'var(--nos-palette-red800)',
    red900: 'var(--nos-palette-red900)'
  },
  color: {
    brand: {
      primary: 'var(--nos-color-brand-primary)',
      light: 'var(--nos-color-brand-light)',
      lighter: 'var(--nos-color-brand-lighter)',
      dark: 'var(--nos-color-brand-dark)',
      darker: 'var(--nos-color-brand-darker)'
    },
    background: {
      default: 'var(--nos-color-background-default)',
      hover: 'var(--nos-color-background-hover)',
      dark: 'var(--nos-color-background-dark)'
    },
    text: {
      body: 'var(--nos-color-text-body)',
      muted: 'var(--nos-color-text-muted)',
      error: 'var(--nos-color-text-error)',
      link: 'var(--nos-color-text-link)'
    },
    border: {
      light: 'var(--nos-color-border-light)',
      muted: 'var(--nos-color-border-muted)'
    }
  },
  spacing: {
    spacer: {
      zero: 'var(--nos-spacing-spacer-zero)',
      xs: 'var(--nos-spacing-spacer-xs)',
      sm: 'var(--nos-spacing-spacer-sm)',
      md: 'var(--nos-spacing-spacer-md)',
      lg: 'var(--nos-spacing-spacer-lg)',
      xl: 'var(--nos-spacing-spacer-xl)',
      xxl: 'var(--nos-spacing-spacer-xxl)'
    }
  },
  size: {
    borderRadius: {
      xs: 'var(--nos-size-borderRadius-xs)',
      sm: 'var(--nos-size-borderRadius-sm)',
      md: 'var(--nos-size-borderRadius-md)',
      lg: 'var(--nos-size-borderRadius-lg)',
      xl: 'var(--nos-size-borderRadius-xl)'
    }
  },
  shadow: {
    sm: 'var(--nos-shadow-sm)',
    md: 'var(--nos-shadow-md)',
    lg: 'var(--nos-shadow-lg)'
  },
  font: {
    family: {
      system: 'var(--nos-font-family-system)',
      monospace: 'var(--nos-font-family-monospace)',
      display: 'var(--nos-font-family-display)',
      size: {
        f00: 'var(--nos-font-family-size-f00)',
        f0: 'var(--nos-font-family-size-f0)',
        f1: 'var(--nos-font-family-size-f1)',
        f2: 'var(--nos-font-family-size-f2)',
        f3: 'var(--nos-font-family-size-f3)',
        f4: 'var(--nos-font-family-size-f4)',
        f5: 'var(--nos-font-family-size-f5)',
        f6: 'var(--nos-font-family-size-f6)'
      },
      lineHeight: {
        xs: 'var(--nos-font-family-lineHeight-xs)',
        sm: 'var(--nos-font-family-lineHeight-sm)',
        md: 'var(--nos-font-family-lineHeight-md)',
        default: 'var(--nos-font-family-lineHeight-default)',
        lg: 'var(--nos-font-family-lineHeight-lg)',
        xl: 'var(--nos-font-family-lineHeight-xl)'
      }
    }
  }
} as const;