/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'palette.black': '#212529',
  'palette.white': '#ffffff',
  'palette.gray25': '#f8f9fa',
  'palette.gray50': '#f1f3f5',
  'palette.gray100': '#e5e8ec',
  'palette.gray200': '#d0d6dd',
  'palette.gray300': '#bbc2ca',
  'palette.gray400': '#a7aeb6',
  'palette.gray500': '#9299a1',
  'palette.gray600': '#828990',
  'palette.gray700': '#6f757c',
  'palette.gray800': '#5c6167',
  'palette.gray900': '#474b4f',
  'palette.grey50': '#f2f4f8',
  'palette.grey100': '#eceff4',
  'palette.grey200': '#e5e9f0',
  'palette.grey300': '#d8dee9',
  'palette.grey400': '#afb8c1',
  'palette.grey500': '#6e7781',
  'palette.grey600': '#4c566a',
  'palette.grey700': '#434c5e',
  'palette.grey800': '#434c5e',
  'palette.grey900': '#2e3440',
  'palette.teal50': '#e6fcf5',
  'palette.teal100': '#c7f1e5',
  'palette.teal200': '#93e5cc',
  'palette.teal300': '#58d7b1',
  'palette.teal400': '#1fc393',
  'palette.teal500': '#1bac81',
  'palette.teal600': '#189973',
  'palette.teal700': '#158363',
  'palette.teal800': '#116c52',
  'palette.teal900': '#0d5540',
  'palette.green50': '#dafbe1',
  'palette.green100': '#aceebb',
  'palette.green200': '#6fdd8b',
  'palette.green300': '#4ac26b',
  'palette.green400': '#2da44e',
  'palette.green500': '#1a7f37',
  'palette.green600': '#116329',
  'palette.green700': '#044f1e',
  'palette.green800': '#003d16',
  'palette.green900': '#002d11',
  'palette.blue50': '#edf2ff',
  'palette.blue100': '#e2e7fe',
  'palette.blue200': '#cad4fd',
  'palette.blue300': '#b0bffd',
  'palette.blue400': '#95a9fc',
  'palette.blue500': '#7791fb',
  'palette.blue600': '#5f7efa',
  'palette.blue700': '#506cdb',
  'palette.blue800': '#4259b4',
  'palette.blue900': '#34458c',
  'palette.orange50': '#fff9db',
  'palette.orange100': '#ffe4ca',
  'palette.orange200': '#ffcb9b',
  'palette.orange300': '#ffb066',
  'palette.orange400': '#fe912b',
  'palette.orange500': '#df7f26',
  'palette.orange600': '#c77222',
  'palette.orange700': '#ab621d',
  'palette.orange800': '#8e5118',
  'palette.orange900': '#6d3e12',
  'palette.red50': '#fff5f5',
  'palette.red100': '#ffe1e1',
  'palette.red200': '#ffc7c7',
  'palette.red300': '#ffabab',
  'palette.red400': '#ff8b8b',
  'palette.red500': '#f76868',
  'palette.red600': '#dd5d5d',
  'palette.red700': '#be5050',
  'palette.red800': '#9d4242',
  'palette.red900': '#793333',
  'color.brand.primary': '#1bac81',
  'color.brand.light': '#93e5cc',
  'color.brand.lighter': '#e6fcf5',
  'color.brand.dark': '#189973',
  'color.brand.darker': '#116c52',
  'color.background.default': '#f8f9fa',
  'color.background.hover': '#f1f3f5',
  'color.background.dark': '#e5e8ec',
  'color.text.body': '#212529',
  'color.text.muted': '#6e7781',
  'color.text.error': '#be5050',
  'color.text.link': '#506cdb',
  'color.border.light': '#bbc2ca',
  'color.border.muted': '#eceff4',
  'spacing.spacer.zero': '0',
  'spacing.spacer.xs': '4px',
  'spacing.spacer.sm': '8px',
  'spacing.spacer.md': '16px',
  'spacing.spacer.lg': '24px',
  'spacing.spacer.xl': '32px',
  'spacing.spacer.xxl': '40px',
  'size.borderRadius.xs': '2px',
  'size.borderRadius.sm': '4px',
  'size.borderRadius.md': '6px',
  'size.borderRadius.lg': '8px',
  'size.borderRadius.xl': '10px',
  'shadow.sm': {
    offsetX: '0',
    offsetY: '8px',
    blur: '16px',
    spread: '0',
    color: '#64646f33',
  },
  'shadow.md': {
    offsetX: '0',
    offsetY: '12px',
    blur: '24px',
    spread: '0',
    color: '#64646f33',
  },
  'shadow.lg': {
    offsetX: '0',
    offsetY: '16px',
    blur: '30px',
    spread: '0',
    color: '#64646f33',
  },
  'font.family.system': ['-apple-system,', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
  'font.family.monospace': ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'Courier', 'monospace'],
  'font.family.display': ['InterUI', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Segoe UI', 'Oxygen', 'Ubuntu', 'Cantarell', 'Open Sans', 'sans-serif'],
  'font.family.size.f00': '32px',
  'font.family.size.f0': '32px',
  'font.family.size.f1': '26px',
  'font.family.size.f2': '22px',
  'font.family.size.f3': '16px',
  'font.family.size.f4': '16px',
  'font.family.size.f5': '14px',
  'font.family.size.f6': '12px',
  'font.family.lineHeight.xs': '1',
  'font.family.lineHeight.sm': '1.25',
  'font.family.lineHeight.md': '1.5',
  'font.family.lineHeight.default': '1.5',
  'font.family.lineHeight.lg': '1.8',
  'font.family.lineHeight.xl': '2',
};

export const meta = {
  'palette.black': {
    '_original': {
      '$value': '#212529',
      '$extensions': {
        mode: {
          light: '#212529',
          dark: '#010409',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.black',
    '$type': 'color',
    '$value': '#212529',
    '$extensions': {
      mode: {
        light: '#212529',
        dark: '#010409',
      },
    },
  },
  'palette.white': {
    '_original': {
      '$value': '#ffffff',
      '$extensions': {
        mode: {
          light: '#ffffff',
          dark: '#f0f6fc',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.white',
    '$type': 'color',
    '$value': '#ffffff',
    '$extensions': {
      mode: {
        light: '#ffffff',
        dark: '#f0f6fc',
      },
    },
  },
  'palette.gray25': {
    '_original': {
      '$value': '#f8f9fa',
      '$extensions': {
        mode: {
          light: '#f8f9fa',
          dark: '#f0f6fc',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray25',
    '$type': 'color',
    '$value': '#f8f9fa',
    '$extensions': {
      mode: {
        light: '#f8f9fa',
        dark: '#f0f6fc',
      },
    },
  },
  'palette.gray50': {
    '_original': {
      '$value': '#f1f3f5',
      '$extensions': {
        mode: {
          light: '#f1f3f5',
          dark: '#f0f6fc',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray50',
    '$type': 'color',
    '$value': '#f1f3f5',
    '$extensions': {
      mode: {
        light: '#f1f3f5',
        dark: '#f0f6fc',
      },
    },
  },
  'palette.gray100': {
    '_original': {
      '$value': '#e5e8ec',
      '$extensions': {
        mode: {
          light: '#e5e8ec',
          dark: '#c9d1d9',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray100',
    '$type': 'color',
    '$value': '#e5e8ec',
    '$extensions': {
      mode: {
        light: '#e5e8ec',
        dark: '#c9d1d9',
      },
    },
  },
  'palette.gray200': {
    '_original': {
      '$value': '#d0d6dd',
      '$extensions': {
        mode: {
          light: '#d0d6dd',
          dark: '#b1bac4',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray200',
    '$type': 'color',
    '$value': '#d0d6dd',
    '$extensions': {
      mode: {
        light: '#d0d6dd',
        dark: '#b1bac4',
      },
    },
  },
  'palette.gray300': {
    '_original': {
      '$value': '#bbc2ca',
      '$extensions': {
        mode: {
          light: '#bbc2ca',
          dark: '#8b949e',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray300',
    '$type': 'color',
    '$value': '#bbc2ca',
    '$extensions': {
      mode: {
        light: '#bbc2ca',
        dark: '#8b949e',
      },
    },
  },
  'palette.gray400': {
    '_original': {
      '$value': '#a7aeb6',
      '$extensions': {
        mode: {
          light: '#a7aeb6',
          dark: '#6e7681',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray400',
    '$type': 'color',
    '$value': '#a7aeb6',
    '$extensions': {
      mode: {
        light: '#a7aeb6',
        dark: '#6e7681',
      },
    },
  },
  'palette.gray500': {
    '_original': {
      '$value': '#9299a1',
      '$extensions': {
        mode: {
          light: '#9299a1',
          dark: '#484f58',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray500',
    '$type': 'color',
    '$value': '#9299a1',
    '$extensions': {
      mode: {
        light: '#9299a1',
        dark: '#484f58',
      },
    },
  },
  'palette.gray600': {
    '_original': {
      '$value': '#828990',
      '$extensions': {
        mode: {
          light: '#828990',
          dark: '#30363d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray600',
    '$type': 'color',
    '$value': '#828990',
    '$extensions': {
      mode: {
        light: '#828990',
        dark: '#30363d',
      },
    },
  },
  'palette.gray700': {
    '_original': {
      '$value': '#6f757c',
      '$extensions': {
        mode: {
          light: '#6f757c',
          dark: '#21262d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray700',
    '$type': 'color',
    '$value': '#6f757c',
    '$extensions': {
      mode: {
        light: '#6f757c',
        dark: '#21262d',
      },
    },
  },
  'palette.gray800': {
    '_original': {
      '$value': '#5c6167',
      '$extensions': {
        mode: {
          light: '#5c6167',
          dark: '#161b22',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray800',
    '$type': 'color',
    '$value': '#5c6167',
    '$extensions': {
      mode: {
        light: '#5c6167',
        dark: '#161b22',
      },
    },
  },
  'palette.gray900': {
    '_original': {
      '$value': '#474b4f',
      '$extensions': {
        mode: {
          light: '#474b4f',
          dark: '#0d1117',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray900',
    '$type': 'color',
    '$value': '#474b4f',
    '$extensions': {
      mode: {
        light: '#474b4f',
        dark: '#0d1117',
      },
    },
  },
  'palette.grey50': {
    '_original': {
      '$value': '#f2f4f8',
      '$extensions': {
        mode: {
          light: '#f2f4f8',
          dark: '#f0f6fc',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey50',
    '$type': 'color',
    '$value': '#f2f4f8',
    '$extensions': {
      mode: {
        light: '#f2f4f8',
        dark: '#f0f6fc',
      },
    },
  },
  'palette.grey100': {
    '_original': {
      '$value': '#ECEFF4',
      '$extensions': {
        mode: {
          light: '#ECEFF4',
          dark: '#c9d1d9',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey100',
    '$type': 'color',
    '$value': '#eceff4',
    '$extensions': {
      mode: {
        light: '#eceff4',
        dark: '#c9d1d9',
      },
    },
  },
  'palette.grey200': {
    '_original': {
      '$value': '#E5E9F0',
      '$extensions': {
        mode: {
          light: '#E5E9F0',
          dark: '#b1bac4',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey200',
    '$type': 'color',
    '$value': '#e5e9f0',
    '$extensions': {
      mode: {
        light: '#e5e9f0',
        dark: '#b1bac4',
      },
    },
  },
  'palette.grey300': {
    '_original': {
      '$value': '#D8DEE9',
      '$extensions': {
        mode: {
          light: '#D8DEE9',
          dark: '#8b949e',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey300',
    '$type': 'color',
    '$value': '#d8dee9',
    '$extensions': {
      mode: {
        light: '#d8dee9',
        dark: '#8b949e',
      },
    },
  },
  'palette.grey400': {
    '_original': {
      '$value': '#afb8c1',
      '$extensions': {
        mode: {
          light: '#afb8c1',
          dark: '#6e7681',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey400',
    '$type': 'color',
    '$value': '#afb8c1',
    '$extensions': {
      mode: {
        light: '#afb8c1',
        dark: '#6e7681',
      },
    },
  },
  'palette.grey500': {
    '_original': {
      '$value': '#6e7781',
      '$extensions': {
        mode: {
          light: '#6e7781',
          dark: '#484f58',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey500',
    '$type': 'color',
    '$value': '#6e7781',
    '$extensions': {
      mode: {
        light: '#6e7781',
        dark: '#484f58',
      },
    },
  },
  'palette.grey600': {
    '_original': {
      '$value': '#4C566A',
      '$extensions': {
        mode: {
          light: '#4C566A',
          dark: '#30363d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey600',
    '$type': 'color',
    '$value': '#4c566a',
    '$extensions': {
      mode: {
        light: '#4c566a',
        dark: '#30363d',
      },
    },
  },
  'palette.grey700': {
    '_original': {
      '$value': '#434C5E',
      '$extensions': {
        mode: {
          light: '#434C5E',
          dark: '#21262d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey700',
    '$type': 'color',
    '$value': '#434c5e',
    '$extensions': {
      mode: {
        light: '#434c5e',
        dark: '#21262d',
      },
    },
  },
  'palette.grey800': {
    '_original': {
      '$value': '#434C5E',
      '$extensions': {
        mode: {
          light: '#434C5E',
          dark: '#161b22',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey800',
    '$type': 'color',
    '$value': '#434c5e',
    '$extensions': {
      mode: {
        light: '#434c5e',
        dark: '#161b22',
      },
    },
  },
  'palette.grey900': {
    '_original': {
      '$value': '#2E3440',
      '$extensions': {
        mode: {
          light: '#2E3440',
          dark: '#0d1117',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.grey900',
    '$type': 'color',
    '$value': '#2e3440',
    '$extensions': {
      mode: {
        light: '#2e3440',
        dark: '#0d1117',
      },
    },
  },
  'palette.teal50': {
    '_original': {
      '$value': '#e6fcf5',
      '$extensions': {
        mode: {
          light: '#e6fcf5',
          dark: '#aff5b4',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal50',
    '$type': 'color',
    '$value': '#e6fcf5',
    '$extensions': {
      mode: {
        light: '#e6fcf5',
        dark: '#aff5b4',
      },
    },
  },
  'palette.teal100': {
    '_original': {
      '$value': '#c7f1e5',
      '$extensions': {
        mode: {
          light: '#c7f1e5',
          dark: '#7ee787',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal100',
    '$type': 'color',
    '$value': '#c7f1e5',
    '$extensions': {
      mode: {
        light: '#c7f1e5',
        dark: '#7ee787',
      },
    },
  },
  'palette.teal200': {
    '_original': {
      '$value': '#93e5cc',
      '$extensions': {
        mode: {
          light: '#93e5cc',
          dark: '#56d364',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal200',
    '$type': 'color',
    '$value': '#93e5cc',
    '$extensions': {
      mode: {
        light: '#93e5cc',
        dark: '#56d364',
      },
    },
  },
  'palette.teal300': {
    '_original': {
      '$value': '#58d7b1',
      '$extensions': {
        mode: {
          light: '#58d7b1',
          dark: '#3fb950',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal300',
    '$type': 'color',
    '$value': '#58d7b1',
    '$extensions': {
      mode: {
        light: '#58d7b1',
        dark: '#3fb950',
      },
    },
  },
  'palette.teal400': {
    '_original': {
      '$value': '#1fc393',
      '$extensions': {
        mode: {
          light: '#1fc393',
          dark: '#2ea043',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal400',
    '$type': 'color',
    '$value': '#1fc393',
    '$extensions': {
      mode: {
        light: '#1fc393',
        dark: '#2ea043',
      },
    },
  },
  'palette.teal500': {
    '_original': {
      '$value': '#1bac81',
      '$extensions': {
        mode: {
          light: '#1bac81',
          dark: '#238636',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal500',
    '$type': 'color',
    '$value': '#1bac81',
    '$extensions': {
      mode: {
        light: '#1bac81',
        dark: '#238636',
      },
    },
  },
  'palette.teal600': {
    '_original': {
      '$value': '#189973',
      '$extensions': {
        mode: {
          light: '#189973',
          dark: '#196c2e',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal600',
    '$type': 'color',
    '$value': '#189973',
    '$extensions': {
      mode: {
        light: '#189973',
        dark: '#196c2e',
      },
    },
  },
  'palette.teal700': {
    '_original': {
      '$value': '#158363',
      '$extensions': {
        mode: {
          light: '#158363',
          dark: '#0f5323',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal700',
    '$type': 'color',
    '$value': '#158363',
    '$extensions': {
      mode: {
        light: '#158363',
        dark: '#0f5323',
      },
    },
  },
  'palette.teal800': {
    '_original': {
      '$value': '#116c52',
      '$extensions': {
        mode: {
          light: '#116c52',
          dark: '#033a16',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal800',
    '$type': 'color',
    '$value': '#116c52',
    '$extensions': {
      mode: {
        light: '#116c52',
        dark: '#033a16',
      },
    },
  },
  'palette.teal900': {
    '_original': {
      '$value': '#0d5540',
      '$extensions': {
        mode: {
          light: '#0d5540',
          dark: '#04260f',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.teal900',
    '$type': 'color',
    '$value': '#0d5540',
    '$extensions': {
      mode: {
        light: '#0d5540',
        dark: '#04260f',
      },
    },
  },
  'palette.green50': {
    '_original': {
      '$value': '#dafbe1',
      '$extensions': {
        mode: {
          light: '#dafbe1',
          dark: '#aff5b4',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green50',
    '$type': 'color',
    '$value': '#dafbe1',
    '$extensions': {
      mode: {
        light: '#dafbe1',
        dark: '#aff5b4',
      },
    },
  },
  'palette.green100': {
    '_original': {
      '$value': '#aceebb',
      '$extensions': {
        mode: {
          light: '#aceebb',
          dark: '#7ee787',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green100',
    '$type': 'color',
    '$value': '#aceebb',
    '$extensions': {
      mode: {
        light: '#aceebb',
        dark: '#7ee787',
      },
    },
  },
  'palette.green200': {
    '_original': {
      '$value': '#6fdd8b',
      '$extensions': {
        mode: {
          light: '#6fdd8b',
          dark: '#56d364',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green200',
    '$type': 'color',
    '$value': '#6fdd8b',
    '$extensions': {
      mode: {
        light: '#6fdd8b',
        dark: '#56d364',
      },
    },
  },
  'palette.green300': {
    '_original': {
      '$value': '#4ac26b',
      '$extensions': {
        mode: {
          light: '#4ac26b',
          dark: '#3fb950',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green300',
    '$type': 'color',
    '$value': '#4ac26b',
    '$extensions': {
      mode: {
        light: '#4ac26b',
        dark: '#3fb950',
      },
    },
  },
  'palette.green400': {
    '_original': {
      '$value': '#2da44e',
      '$extensions': {
        mode: {
          light: '#2da44e',
          dark: '#2ea043',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green400',
    '$type': 'color',
    '$value': '#2da44e',
    '$extensions': {
      mode: {
        light: '#2da44e',
        dark: '#2ea043',
      },
    },
  },
  'palette.green500': {
    '_original': {
      '$value': '#1a7f37',
      '$extensions': {
        mode: {
          light: '#1a7f37',
          dark: '#238636',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green500',
    '$type': 'color',
    '$value': '#1a7f37',
    '$extensions': {
      mode: {
        light: '#1a7f37',
        dark: '#238636',
      },
    },
  },
  'palette.green600': {
    '_original': {
      '$value': '#116329',
      '$extensions': {
        mode: {
          light: '#116329',
          dark: '#196c2e',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green600',
    '$type': 'color',
    '$value': '#116329',
    '$extensions': {
      mode: {
        light: '#116329',
        dark: '#196c2e',
      },
    },
  },
  'palette.green700': {
    '_original': {
      '$value': '#044f1e',
      '$extensions': {
        mode: {
          light: '#044f1e',
          dark: '#0f5323',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green700',
    '$type': 'color',
    '$value': '#044f1e',
    '$extensions': {
      mode: {
        light: '#044f1e',
        dark: '#0f5323',
      },
    },
  },
  'palette.green800': {
    '_original': {
      '$value': '#003d16',
      '$extensions': {
        mode: {
          light: '#003d16',
          dark: '#033a16',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green800',
    '$type': 'color',
    '$value': '#003d16',
    '$extensions': {
      mode: {
        light: '#003d16',
        dark: '#033a16',
      },
    },
  },
  'palette.green900': {
    '_original': {
      '$value': '#002d11',
      '$extensions': {
        mode: {
          light: '#002d11',
          dark: '#04260f',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green900',
    '$type': 'color',
    '$value': '#002d11',
    '$extensions': {
      mode: {
        light: '#002d11',
        dark: '#04260f',
      },
    },
  },
  'palette.blue50': {
    '_original': {
      '$value': '#edf2ff',
      '$extensions': {
        mode: {
          light: '#edf2ff',
          dark: '#cae8ff',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue50',
    '$type': 'color',
    '$value': '#edf2ff',
    '$extensions': {
      mode: {
        light: '#edf2ff',
        dark: '#cae8ff',
      },
    },
  },
  'palette.blue100': {
    '_original': {
      '$value': '#e2e7fe',
      '$extensions': {
        mode: {
          light: '#e2e7fe',
          dark: '#a5d6ff',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue100',
    '$type': 'color',
    '$value': '#e2e7fe',
    '$extensions': {
      mode: {
        light: '#e2e7fe',
        dark: '#a5d6ff',
      },
    },
  },
  'palette.blue200': {
    '_original': {
      '$value': '#cad4fd',
      '$extensions': {
        mode: {
          light: '#cad4fd',
          dark: '#79c0ff',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue200',
    '$type': 'color',
    '$value': '#cad4fd',
    '$extensions': {
      mode: {
        light: '#cad4fd',
        dark: '#79c0ff',
      },
    },
  },
  'palette.blue300': {
    '_original': {
      '$value': '#b0bffd',
      '$extensions': {
        mode: {
          light: '#b0bffd',
          dark: '#58a6ff',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue300',
    '$type': 'color',
    '$value': '#b0bffd',
    '$extensions': {
      mode: {
        light: '#b0bffd',
        dark: '#58a6ff',
      },
    },
  },
  'palette.blue400': {
    '_original': {
      '$value': '#95a9fc',
      '$extensions': {
        mode: {
          light: '#95a9fc',
          dark: '#388bfd',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue400',
    '$type': 'color',
    '$value': '#95a9fc',
    '$extensions': {
      mode: {
        light: '#95a9fc',
        dark: '#388bfd',
      },
    },
  },
  'palette.blue500': {
    '_original': {
      '$value': '#7791fb',
      '$extensions': {
        mode: {
          light: '#7791fb',
          dark: '#1f6feb',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue500',
    '$type': 'color',
    '$value': '#7791fb',
    '$extensions': {
      mode: {
        light: '#7791fb',
        dark: '#1f6feb',
      },
    },
  },
  'palette.blue600': {
    '_original': {
      '$value': '#5f7efa',
      '$extensions': {
        mode: {
          light: '#5f7efa',
          dark: '#1158c7',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue600',
    '$type': 'color',
    '$value': '#5f7efa',
    '$extensions': {
      mode: {
        light: '#5f7efa',
        dark: '#1158c7',
      },
    },
  },
  'palette.blue700': {
    '_original': {
      '$value': '#506cdb',
      '$extensions': {
        mode: {
          light: '#506cdb',
          dark: '#0d419d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue700',
    '$type': 'color',
    '$value': '#506cdb',
    '$extensions': {
      mode: {
        light: '#506cdb',
        dark: '#0d419d',
      },
    },
  },
  'palette.blue800': {
    '_original': {
      '$value': '#4259b4',
      '$extensions': {
        mode: {
          light: '#4259b4',
          dark: '#0c2d6b',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue800',
    '$type': 'color',
    '$value': '#4259b4',
    '$extensions': {
      mode: {
        light: '#4259b4',
        dark: '#0c2d6b',
      },
    },
  },
  'palette.blue900': {
    '_original': {
      '$value': '#34458c',
      '$extensions': {
        mode: {
          light: '#34458c',
          dark: '#051d4d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue900',
    '$type': 'color',
    '$value': '#34458c',
    '$extensions': {
      mode: {
        light: '#34458c',
        dark: '#051d4d',
      },
    },
  },
  'palette.orange50': {
    '_original': {
      '$value': '#fff9db',
      '$extensions': {
        mode: {
          light: '#fff9db',
          dark: '#FFDDD2',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange50',
    '$type': 'color',
    '$value': '#fff9db',
    '$extensions': {
      mode: {
        light: '#fff9db',
        dark: '#ffddd2',
      },
    },
  },
  'palette.orange100': {
    '_original': {
      '$value': '#ffe4ca',
      '$extensions': {
        mode: {
          light: '#ffe4ca',
          dark: '#FFC2B2',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange100',
    '$type': 'color',
    '$value': '#ffe4ca',
    '$extensions': {
      mode: {
        light: '#ffe4ca',
        dark: '#ffc2b2',
      },
    },
  },
  'palette.orange200': {
    '_original': {
      '$value': '#ffcb9b',
      '$extensions': {
        mode: {
          light: '#ffcb9b',
          dark: '#FFA28B',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange200',
    '$type': 'color',
    '$value': '#ffcb9b',
    '$extensions': {
      mode: {
        light: '#ffcb9b',
        dark: '#ffa28b',
      },
    },
  },
  'palette.orange300': {
    '_original': {
      '$value': '#ffb066',
      '$extensions': {
        mode: {
          light: '#ffb066',
          dark: '#F78166',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange300',
    '$type': 'color',
    '$value': '#ffb066',
    '$extensions': {
      mode: {
        light: '#ffb066',
        dark: '#f78166',
      },
    },
  },
  'palette.orange400': {
    '_original': {
      '$value': '#fe912b',
      '$extensions': {
        mode: {
          light: '#fe912b',
          dark: '#EA6045',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange400',
    '$type': 'color',
    '$value': '#fe912b',
    '$extensions': {
      mode: {
        light: '#fe912b',
        dark: '#ea6045',
      },
    },
  },
  'palette.orange500': {
    '_original': {
      '$value': '#df7f26',
      '$extensions': {
        mode: {
          light: '#df7f26',
          dark: '#CF462D',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange500',
    '$type': 'color',
    '$value': '#df7f26',
    '$extensions': {
      mode: {
        light: '#df7f26',
        dark: '#cf462d',
      },
    },
  },
  'palette.orange600': {
    '_original': {
      '$value': '#c77222',
      '$extensions': {
        mode: {
          light: '#c77222',
          dark: '#AC3220',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange600',
    '$type': 'color',
    '$value': '#c77222',
    '$extensions': {
      mode: {
        light: '#c77222',
        dark: '#ac3220',
      },
    },
  },
  'palette.orange700': {
    '_original': {
      '$value': '#ab621d',
      '$extensions': {
        mode: {
          light: '#ab621d',
          dark: '#872012',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange700',
    '$type': 'color',
    '$value': '#ab621d',
    '$extensions': {
      mode: {
        light: '#ab621d',
        dark: '#872012',
      },
    },
  },
  'palette.orange800': {
    '_original': {
      '$value': '#8e5118',
      '$extensions': {
        mode: {
          light: '#8e5118',
          dark: '#640D04',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange800',
    '$type': 'color',
    '$value': '#8e5118',
    '$extensions': {
      mode: {
        light: '#8e5118',
        dark: '#640d04',
      },
    },
  },
  'palette.orange900': {
    '_original': {
      '$value': '#6d3e12',
      '$extensions': {
        mode: {
          light: '#6d3e12',
          dark: '#460701',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.orange900',
    '$type': 'color',
    '$value': '#6d3e12',
    '$extensions': {
      mode: {
        light: '#6d3e12',
        dark: '#460701',
      },
    },
  },
  'palette.red50': {
    '_original': {
      '$value': '#fff5f5',
      '$extensions': {
        mode: {
          light: '#fff5f5',
          dark: '#ffc1ba',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red50',
    '$type': 'color',
    '$value': '#fff5f5',
    '$extensions': {
      mode: {
        light: '#fff5f5',
        dark: '#ffc1ba',
      },
    },
  },
  'palette.red100': {
    '_original': {
      '$value': '#ffe1e1',
      '$extensions': {
        mode: {
          light: '#ffe1e1',
          dark: '#ffc1ba',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red100',
    '$type': 'color',
    '$value': '#ffe1e1',
    '$extensions': {
      mode: {
        light: '#ffe1e1',
        dark: '#ffc1ba',
      },
    },
  },
  'palette.red200': {
    '_original': {
      '$value': '#ffc7c7',
      '$extensions': {
        mode: {
          light: '#ffc7c7',
          dark: '#ffa198',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red200',
    '$type': 'color',
    '$value': '#ffc7c7',
    '$extensions': {
      mode: {
        light: '#ffc7c7',
        dark: '#ffa198',
      },
    },
  },
  'palette.red300': {
    '_original': {
      '$value': '#ffabab',
      '$extensions': {
        mode: {
          light: '#ffabab',
          dark: '#ff7b72',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red300',
    '$type': 'color',
    '$value': '#ffabab',
    '$extensions': {
      mode: {
        light: '#ffabab',
        dark: '#ff7b72',
      },
    },
  },
  'palette.red400': {
    '_original': {
      '$value': '#ff8b8b',
      '$extensions': {
        mode: {
          light: '#ff8b8b',
          dark: '#f85149',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red400',
    '$type': 'color',
    '$value': '#ff8b8b',
    '$extensions': {
      mode: {
        light: '#ff8b8b',
        dark: '#f85149',
      },
    },
  },
  'palette.red500': {
    '_original': {
      '$value': '#f76868',
      '$extensions': {
        mode: {
          light: '#f76868',
          dark: '#da3633',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red500',
    '$type': 'color',
    '$value': '#f76868',
    '$extensions': {
      mode: {
        light: '#f76868',
        dark: '#da3633',
      },
    },
  },
  'palette.red600': {
    '_original': {
      '$value': '#dd5d5d',
      '$extensions': {
        mode: {
          light: '#dd5d5d',
          dark: '#b62324',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red600',
    '$type': 'color',
    '$value': '#dd5d5d',
    '$extensions': {
      mode: {
        light: '#dd5d5d',
        dark: '#b62324',
      },
    },
  },
  'palette.red700': {
    '_original': {
      '$value': '#be5050',
      '$extensions': {
        mode: {
          light: '#be5050',
          dark: '#8e1519',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red700',
    '$type': 'color',
    '$value': '#be5050',
    '$extensions': {
      mode: {
        light: '#be5050',
        dark: '#8e1519',
      },
    },
  },
  'palette.red800': {
    '_original': {
      '$value': '#9d4242',
      '$extensions': {
        mode: {
          light: '#9d4242',
          dark: '#67060c',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red800',
    '$type': 'color',
    '$value': '#9d4242',
    '$extensions': {
      mode: {
        light: '#9d4242',
        dark: '#67060c',
      },
    },
  },
  'palette.red900': {
    '_original': {
      '$value': '#793333',
      '$extensions': {
        mode: {
          light: '#793333',
          dark: '#490202',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red900',
    '$type': 'color',
    '$value': '#793333',
    '$extensions': {
      mode: {
        light: '#793333',
        dark: '#490202',
      },
    },
  },
  'color.brand.primary': {
    '_original': {
      '$value': '{palette.teal500}',
    },
    '_group': {
      id: 'color.brand',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.brand.primary',
    '$type': 'color',
    '$value': '#1bac81',
  },
  'color.brand.light': {
    '_original': {
      '$value': '{palette.teal200}',
    },
    '_group': {
      id: 'color.brand',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.brand.light',
    '$type': 'color',
    '$value': '#93e5cc',
  },
  'color.brand.lighter': {
    '_original': {
      '$value': '{palette.teal50}',
    },
    '_group': {
      id: 'color.brand',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.brand.lighter',
    '$type': 'color',
    '$value': '#e6fcf5',
  },
  'color.brand.dark': {
    '_original': {
      '$value': '{palette.teal600}',
    },
    '_group': {
      id: 'color.brand',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.brand.dark',
    '$type': 'color',
    '$value': '#189973',
  },
  'color.brand.darker': {
    '_original': {
      '$value': '{palette.teal800}',
    },
    '_group': {
      id: 'color.brand',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.brand.darker',
    '$type': 'color',
    '$value': '#116c52',
  },
  'color.background.default': {
    '_original': {
      '$value': '{palette.gray25}',
    },
    '_group': {
      id: 'color.background',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.background.default',
    '$type': 'color',
    '$value': '#f8f9fa',
  },
  'color.background.hover': {
    '_original': {
      '$value': '{palette.gray50}',
    },
    '_group': {
      id: 'color.background',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.background.hover',
    '$type': 'color',
    '$value': '#f1f3f5',
  },
  'color.background.dark': {
    '_original': {
      '$value': '{palette.gray100}',
    },
    '_group': {
      id: 'color.background',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.background.dark',
    '$type': 'color',
    '$value': '#e5e8ec',
  },
  'color.text.body': {
    '_original': {
      '$value': '{palette.black}',
    },
    '_group': {
      id: 'color.text',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.text.body',
    '$type': 'color',
    '$value': '#212529',
  },
  'color.text.muted': {
    '_original': {
      '$value': '{palette.grey500}',
    },
    '_group': {
      id: 'color.text',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.text.muted',
    '$type': 'color',
    '$value': '#6e7781',
  },
  'color.text.error': {
    '_original': {
      '$value': '{palette.red700}',
    },
    '_group': {
      id: 'color.text',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.text.error',
    '$type': 'color',
    '$value': '#be5050',
  },
  'color.text.link': {
    '_original': {
      '$value': '{palette.blue700}',
    },
    '_group': {
      id: 'color.text',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.text.link',
    '$type': 'color',
    '$value': '#506cdb',
  },
  'color.border.light': {
    '_original': {
      '$value': '{palette.gray300}',
    },
    '_group': {
      id: 'color.border',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.border.light',
    '$type': 'color',
    '$value': '#bbc2ca',
  },
  'color.border.muted': {
    '_original': {
      '$value': '{palette.grey100}',
    },
    '_group': {
      id: 'color.border',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.border.muted',
    '$type': 'color',
    '$value': '#eceff4',
  },
  'spacing.spacer.zero': {
    '_original': {
      '$value': '0px',
    },
    '_group': {
      id: 'spacing.spacer',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacer.zero',
    '$type': 'dimension',
    '$value': '0',
  },
  'spacing.spacer.xs': {
    '_original': {
      '$value': '4px',
    },
    '_group': {
      id: 'spacing.spacer',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacer.xs',
    '$type': 'dimension',
    '$value': '4px',
  },
  'spacing.spacer.sm': {
    '_original': {
      '$value': '8px',
    },
    '_group': {
      id: 'spacing.spacer',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacer.sm',
    '$type': 'dimension',
    '$value': '8px',
  },
  'spacing.spacer.md': {
    '_original': {
      '$value': '16px',
    },
    '_group': {
      id: 'spacing.spacer',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacer.md',
    '$type': 'dimension',
    '$value': '16px',
  },
  'spacing.spacer.lg': {
    '_original': {
      '$value': '24px',
    },
    '_group': {
      id: 'spacing.spacer',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacer.lg',
    '$type': 'dimension',
    '$value': '24px',
  },
  'spacing.spacer.xl': {
    '_original': {
      '$value': '32px',
    },
    '_group': {
      id: 'spacing.spacer',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacer.xl',
    '$type': 'dimension',
    '$value': '32px',
  },
  'spacing.spacer.xxl': {
    '_original': {
      '$value': '40px',
    },
    '_group': {
      id: 'spacing.spacer',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacer.xxl',
    '$type': 'dimension',
    '$value': '40px',
  },
  'size.borderRadius.xs': {
    '_original': {
      '$value': '2px',
    },
    '_group': {
      id: 'size.borderRadius',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'size.borderRadius.xs',
    '$type': 'dimension',
    '$value': '2px',
  },
  'size.borderRadius.sm': {
    '_original': {
      '$value': '4px',
    },
    '_group': {
      id: 'size.borderRadius',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'size.borderRadius.sm',
    '$type': 'dimension',
    '$value': '4px',
  },
  'size.borderRadius.md': {
    '_original': {
      '$value': '6px',
    },
    '_group': {
      id: 'size.borderRadius',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'size.borderRadius.md',
    '$type': 'dimension',
    '$value': '6px',
  },
  'size.borderRadius.lg': {
    '_original': {
      '$value': '8px',
    },
    '_group': {
      id: 'size.borderRadius',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'size.borderRadius.lg',
    '$type': 'dimension',
    '$value': '8px',
  },
  'size.borderRadius.xl': {
    '_original': {
      '$value': '10px',
    },
    '_group': {
      id: 'size.borderRadius',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'size.borderRadius.xl',
    '$type': 'dimension',
    '$value': '10px',
  },
  'shadow.sm': {
    '_original': {
      '$value': {
        offsetX: '0px',
        offsetY: '8px',
        blur: '16px',
        spread: '0px',
        color: 'rgba(100, 100, 111, 0.2)',
      },
    },
    '_group': {
      id: 'shadow',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'shadow',
    },
    id: 'shadow.sm',
    '$type': 'shadow',
    '$value': {
      offsetX: '0',
      offsetY: '8px',
      blur: '16px',
      spread: '0',
      color: '#64646f33',
    },
  },
  'shadow.md': {
    '_original': {
      '$value': {
        offsetX: '0px',
        offsetY: '12px',
        blur: '24px',
        spread: '0px',
        color: 'rgba(100, 100, 111, 0.2)',
      },
    },
    '_group': {
      id: 'shadow',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'shadow',
    },
    id: 'shadow.md',
    '$type': 'shadow',
    '$value': {
      offsetX: '0',
      offsetY: '12px',
      blur: '24px',
      spread: '0',
      color: '#64646f33',
    },
  },
  'shadow.lg': {
    '_original': {
      '$value': {
        offsetX: '0px',
        offsetY: '16px',
        blur: '30px',
        spread: '0px',
        color: 'rgba(100, 100, 111, 0.2)',
      },
    },
    '_group': {
      id: 'shadow',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'shadow',
    },
    id: 'shadow.lg',
    '$type': 'shadow',
    '$value': {
      offsetX: '0',
      offsetY: '16px',
      blur: '30px',
      spread: '0',
      color: '#64646f33',
    },
  },
  'font.family.system': {
    '_original': {
      '$value': ['-apple-system,', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
    },
    '_group': {
      id: 'font.family',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'font',
    },
    id: 'font.family.system',
    '$type': 'font',
    '$value': ['-apple-system,', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
  },
  'font.family.monospace': {
    '_original': {
      '$value': ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'Courier', 'monospace'],
    },
    '_group': {
      id: 'font.family',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'font',
    },
    id: 'font.family.monospace',
    '$type': 'font',
    '$value': ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'Courier', 'monospace'],
  },
  'font.family.display': {
    '_original': {
      '$value': ['InterUI', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Segoe UI', 'Oxygen', 'Ubuntu', 'Cantarell', 'Open Sans', 'sans-serif'],
    },
    '_group': {
      id: 'font.family',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'font',
    },
    id: 'font.family.display',
    '$type': 'font',
    '$value': ['InterUI', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Segoe UI', 'Oxygen', 'Ubuntu', 'Cantarell', 'Open Sans', 'sans-serif'],
  },
  'font.family.size.f00': {
    '_original': {
      '$value': '32px',
      '$extensions': {
        mode: {
          mobile: '32px',
          desktop: '48px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f00',
    '$type': 'dimension',
    '$value': '32px',
    '$extensions': {
      mode: {
        mobile: '32px',
        desktop: '48px',
      },
    },
  },
  'font.family.size.f0': {
    '_original': {
      '$value': '32px',
      '$extensions': {
        mode: {
          mobile: '32px',
          desktop: '40px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f0',
    '$type': 'dimension',
    '$value': '32px',
    '$extensions': {
      mode: {
        mobile: '32px',
        desktop: '40px',
      },
    },
  },
  'font.family.size.f1': {
    '_original': {
      '$value': '26px',
      '$extensions': {
        mode: {
          mobile: '26px',
          desktop: '32px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f1',
    '$type': 'dimension',
    '$value': '26px',
    '$extensions': {
      mode: {
        mobile: '26px',
        desktop: '32px',
      },
    },
  },
  'font.family.size.f2': {
    '_original': {
      '$value': '22px',
      '$extensions': {
        mode: {
          mobile: '22px',
          desktop: '24px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f2',
    '$type': 'dimension',
    '$value': '22px',
    '$extensions': {
      mode: {
        mobile: '22px',
        desktop: '24px',
      },
    },
  },
  'font.family.size.f3': {
    '_original': {
      '$value': '16px',
      '$extensions': {
        mode: {
          mobile: '16px',
          desktop: '20px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f3',
    '$type': 'dimension',
    '$value': '16px',
    '$extensions': {
      mode: {
        mobile: '16px',
        desktop: '20px',
      },
    },
  },
  'font.family.size.f4': {
    '_original': {
      '$value': '16px',
      '$extensions': {
        mode: {
          mobile: '16px',
          desktop: '16px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f4',
    '$type': 'dimension',
    '$value': '16px',
    '$extensions': {
      mode: {
        mobile: '16px',
        desktop: '16px',
      },
    },
  },
  'font.family.size.f5': {
    '_original': {
      '$value': '14px',
      '$extensions': {
        mode: {
          mobile: '14px',
          desktop: '14px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f5',
    '$type': 'dimension',
    '$value': '14px',
    '$extensions': {
      mode: {
        mobile: '14px',
        desktop: '14px',
      },
    },
  },
  'font.family.size.f6': {
    '_original': {
      '$value': '12px',
      '$extensions': {
        mode: {
          mobile: '12px',
          desktop: '12px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f6',
    '$type': 'dimension',
    '$value': '12px',
    '$extensions': {
      mode: {
        mobile: '12px',
        desktop: '12px',
      },
    },
  },
  'font.family.lineHeight.xs': {
    '_original': {
      '$value': '1',
    },
    '_group': {
      id: 'font.family.lineHeight',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.lineHeight.xs',
    '$type': 'dimension',
    '$value': '1',
  },
  'font.family.lineHeight.sm': {
    '_original': {
      '$value': '1.25',
    },
    '_group': {
      id: 'font.family.lineHeight',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.lineHeight.sm',
    '$type': 'dimension',
    '$value': '1.25',
  },
  'font.family.lineHeight.md': {
    '_original': {
      '$value': '1.5',
    },
    '_group': {
      id: 'font.family.lineHeight',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.lineHeight.md',
    '$type': 'dimension',
    '$value': '1.5',
  },
  'font.family.lineHeight.default': {
    '_original': {
      '$value': '{font.family.lineHeight.md}',
    },
    '_group': {
      id: 'font.family.lineHeight',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.lineHeight.default',
    '$type': 'dimension',
    '$value': '1.5',
  },
  'font.family.lineHeight.lg': {
    '_original': {
      '$value': '1.8',
    },
    '_group': {
      id: 'font.family.lineHeight',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.lineHeight.lg',
    '$type': 'dimension',
    '$value': '1.8',
  },
  'font.family.lineHeight.xl': {
    '_original': {
      '$value': '2',
    },
    '_group': {
      id: 'font.family.lineHeight',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.lineHeight.xl',
    '$type': 'dimension',
    '$value': '2',
  },
};

export const modes = {
  'palette.black': {
    light: '#212529',
    dark: '#010409',
  },
  'palette.white': {
    light: '#ffffff',
    dark: '#f0f6fc',
  },
  'palette.gray25': {
    light: '#f8f9fa',
    dark: '#f0f6fc',
  },
  'palette.gray50': {
    light: '#f1f3f5',
    dark: '#f0f6fc',
  },
  'palette.gray100': {
    light: '#e5e8ec',
    dark: '#c9d1d9',
  },
  'palette.gray200': {
    light: '#d0d6dd',
    dark: '#b1bac4',
  },
  'palette.gray300': {
    light: '#bbc2ca',
    dark: '#8b949e',
  },
  'palette.gray400': {
    light: '#a7aeb6',
    dark: '#6e7681',
  },
  'palette.gray500': {
    light: '#9299a1',
    dark: '#484f58',
  },
  'palette.gray600': {
    light: '#828990',
    dark: '#30363d',
  },
  'palette.gray700': {
    light: '#6f757c',
    dark: '#21262d',
  },
  'palette.gray800': {
    light: '#5c6167',
    dark: '#161b22',
  },
  'palette.gray900': {
    light: '#474b4f',
    dark: '#0d1117',
  },
  'palette.grey50': {
    light: '#f2f4f8',
    dark: '#f0f6fc',
  },
  'palette.grey100': {
    light: '#eceff4',
    dark: '#c9d1d9',
  },
  'palette.grey200': {
    light: '#e5e9f0',
    dark: '#b1bac4',
  },
  'palette.grey300': {
    light: '#d8dee9',
    dark: '#8b949e',
  },
  'palette.grey400': {
    light: '#afb8c1',
    dark: '#6e7681',
  },
  'palette.grey500': {
    light: '#6e7781',
    dark: '#484f58',
  },
  'palette.grey600': {
    light: '#4c566a',
    dark: '#30363d',
  },
  'palette.grey700': {
    light: '#434c5e',
    dark: '#21262d',
  },
  'palette.grey800': {
    light: '#434c5e',
    dark: '#161b22',
  },
  'palette.grey900': {
    light: '#2e3440',
    dark: '#0d1117',
  },
  'palette.teal50': {
    light: '#e6fcf5',
    dark: '#aff5b4',
  },
  'palette.teal100': {
    light: '#c7f1e5',
    dark: '#7ee787',
  },
  'palette.teal200': {
    light: '#93e5cc',
    dark: '#56d364',
  },
  'palette.teal300': {
    light: '#58d7b1',
    dark: '#3fb950',
  },
  'palette.teal400': {
    light: '#1fc393',
    dark: '#2ea043',
  },
  'palette.teal500': {
    light: '#1bac81',
    dark: '#238636',
  },
  'palette.teal600': {
    light: '#189973',
    dark: '#196c2e',
  },
  'palette.teal700': {
    light: '#158363',
    dark: '#0f5323',
  },
  'palette.teal800': {
    light: '#116c52',
    dark: '#033a16',
  },
  'palette.teal900': {
    light: '#0d5540',
    dark: '#04260f',
  },
  'palette.green50': {
    light: '#dafbe1',
    dark: '#aff5b4',
  },
  'palette.green100': {
    light: '#aceebb',
    dark: '#7ee787',
  },
  'palette.green200': {
    light: '#6fdd8b',
    dark: '#56d364',
  },
  'palette.green300': {
    light: '#4ac26b',
    dark: '#3fb950',
  },
  'palette.green400': {
    light: '#2da44e',
    dark: '#2ea043',
  },
  'palette.green500': {
    light: '#1a7f37',
    dark: '#238636',
  },
  'palette.green600': {
    light: '#116329',
    dark: '#196c2e',
  },
  'palette.green700': {
    light: '#044f1e',
    dark: '#0f5323',
  },
  'palette.green800': {
    light: '#003d16',
    dark: '#033a16',
  },
  'palette.green900': {
    light: '#002d11',
    dark: '#04260f',
  },
  'palette.blue50': {
    light: '#edf2ff',
    dark: '#cae8ff',
  },
  'palette.blue100': {
    light: '#e2e7fe',
    dark: '#a5d6ff',
  },
  'palette.blue200': {
    light: '#cad4fd',
    dark: '#79c0ff',
  },
  'palette.blue300': {
    light: '#b0bffd',
    dark: '#58a6ff',
  },
  'palette.blue400': {
    light: '#95a9fc',
    dark: '#388bfd',
  },
  'palette.blue500': {
    light: '#7791fb',
    dark: '#1f6feb',
  },
  'palette.blue600': {
    light: '#5f7efa',
    dark: '#1158c7',
  },
  'palette.blue700': {
    light: '#506cdb',
    dark: '#0d419d',
  },
  'palette.blue800': {
    light: '#4259b4',
    dark: '#0c2d6b',
  },
  'palette.blue900': {
    light: '#34458c',
    dark: '#051d4d',
  },
  'palette.orange50': {
    light: '#fff9db',
    dark: '#ffddd2',
  },
  'palette.orange100': {
    light: '#ffe4ca',
    dark: '#ffc2b2',
  },
  'palette.orange200': {
    light: '#ffcb9b',
    dark: '#ffa28b',
  },
  'palette.orange300': {
    light: '#ffb066',
    dark: '#f78166',
  },
  'palette.orange400': {
    light: '#fe912b',
    dark: '#ea6045',
  },
  'palette.orange500': {
    light: '#df7f26',
    dark: '#cf462d',
  },
  'palette.orange600': {
    light: '#c77222',
    dark: '#ac3220',
  },
  'palette.orange700': {
    light: '#ab621d',
    dark: '#872012',
  },
  'palette.orange800': {
    light: '#8e5118',
    dark: '#640d04',
  },
  'palette.orange900': {
    light: '#6d3e12',
    dark: '#460701',
  },
  'palette.red50': {
    light: '#fff5f5',
    dark: '#ffc1ba',
  },
  'palette.red100': {
    light: '#ffe1e1',
    dark: '#ffc1ba',
  },
  'palette.red200': {
    light: '#ffc7c7',
    dark: '#ffa198',
  },
  'palette.red300': {
    light: '#ffabab',
    dark: '#ff7b72',
  },
  'palette.red400': {
    light: '#ff8b8b',
    dark: '#f85149',
  },
  'palette.red500': {
    light: '#f76868',
    dark: '#da3633',
  },
  'palette.red600': {
    light: '#dd5d5d',
    dark: '#b62324',
  },
  'palette.red700': {
    light: '#be5050',
    dark: '#8e1519',
  },
  'palette.red800': {
    light: '#9d4242',
    dark: '#67060c',
  },
  'palette.red900': {
    light: '#793333',
    dark: '#490202',
  },
  'font.family.size.f00': {
    mobile: '32px',
    desktop: '48px',
  },
  'font.family.size.f0': {
    mobile: '32px',
    desktop: '40px',
  },
  'font.family.size.f1': {
    mobile: '26px',
    desktop: '32px',
  },
  'font.family.size.f2': {
    mobile: '22px',
    desktop: '24px',
  },
  'font.family.size.f3': {
    mobile: '16px',
    desktop: '20px',
  },
  'font.family.size.f4': {
    mobile: '16px',
    desktop: '16px',
  },
  'font.family.size.f5': {
    mobile: '14px',
    desktop: '14px',
  },
  'font.family.size.f6': {
    mobile: '12px',
    desktop: '12px',
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
