/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'palette.black': '#1d2129',
  'palette.white': '#ffffff',
  'palette.gray0': '#f2f4f8',
  'palette.gray1': '#eceff4',
  'palette.gray2': '#e5e9f0',
  'palette.gray3': '#e5e9f0',
  'palette.gray4': '#afb8c1',
  'palette.gray5': '#6e7781',
  'palette.gray6': '#4c566a',
  'palette.gray7': '#434c5e',
  'palette.gray8': '#434c5e',
  'palette.gray9': '#2e3440',
  'palette.green0': '#dafbe1',
  'palette.green1': '#aceebb',
  'palette.green2': '#6fdd8b',
  'palette.green3': '#4ac26b',
  'palette.green4': '#2da44e',
  'palette.green5': '#1a7f37',
  'palette.green6': '#116329',
  'palette.green7': '#044f1e',
  'palette.green8': '#003d16',
  'palette.green9': '#002d11',
  'palette.blue0': '#ddf4ff',
  'palette.blue1': '#b6e3ff',
  'palette.blue2': '#80ccff',
  'palette.blue3': '#54aeff',
  'palette.blue4': '#218bff',
  'palette.blue5': '#0969da',
  'palette.blue6': '#0550ae',
  'palette.blue7': '#033d8b',
  'palette.blue8': '#0a3069',
  'palette.blue9': '#002155',
  'palette.coral0': '#fff0eb',
  'palette.coral1': '#ffd6cc',
  'palette.coral2': '#ffb4a1',
  'palette.coral3': '#fd8c73',
  'palette.coral4': '#ec6547',
  'palette.coral5': '#c4432b',
  'palette.coral6': '#9e2f1c',
  'palette.coral7': '#801f0f',
  'palette.coral8': '#691105',
  'palette.coral9': '#510901',
  'palette.red0': '#ffebe9',
  'palette.red1': '#ffcecb',
  'palette.red2': '#ffaba8',
  'palette.red3': '#ff8182',
  'palette.red4': '#fa4549',
  'palette.red5': '#cf222e',
  'palette.red6': '#a40e26',
  'palette.red7': '#82071e',
  'palette.red8': '#660018',
  'palette.red9': '#4c0014',
  'color.background': '#f2f4f8',
  'color.text.body': '#1d2129',
  'color.text.muted': '#6e7781',
  'color.text.error': '#82071e',
  'color.text.link': '#0969da',
  'color.border.muted': '#eceff4',
  'spacing.spacer0': '0',
  'spacing.spacerXs': '4px',
  'spacing.spacerS': '8px',
  'spacing.spacerM': '16px',
  'spacing.spacerX': '24px',
  'spacing.spacerXl': '32px',
  'spacing.spacerXxl': '40px',
  'shadow.sm': {
    offsetX: '0',
    offsetY: '8px',
    blur: '16px',
    spread: '0',
    color: '#64646f33',
  },
  'shadow.md': {
    offsetX: '0',
    offsetY: '12px',
    blur: '24px',
    spread: '0',
    color: '#64646f33',
  },
  'shadow.lg': {
    offsetX: '0',
    offsetY: '16px',
    blur: '30px',
    spread: '0',
    color: '#64646f33',
  },
  'font.family.system': ['-apple-system,', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
  'font.family.monospace': ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'Courier', 'monospace'],
  'font.family.display': ['InterUI', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Segoe UI', 'Oxygen', 'Ubuntu', 'Cantarell', 'Open Sans', 'sans-serif'],
  'font.family.size.f00': '32px',
  'font.family.size.f0': '32px',
  'font.family.size.f1': '26px',
  'font.family.size.f2': '22px',
  'font.family.size.f3': '16px',
  'font.family.size.f4': '16px',
  'font.family.size.f5': '14px',
  'font.family.size.f6': '12px',
  'font.family.lineHeight.default': '1.5',
  'font.family.lineHeight.condensed': '1.25',
  'font.family.lineHeight.condensedUltra': '1',
};

export const meta = {
  'palette.black': {
    '_original': {
      '$value': '#1d2129',
      '$extensions': {
        mode: {
          light: '#1d2129',
          dark: '#010409',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.black',
    '$type': 'color',
    '$value': '#1d2129',
    '$extensions': {
      mode: {
        light: '#1d2129',
        dark: '#010409',
      },
    },
  },
  'palette.white': {
    '_original': {
      '$value': '#ffffff',
      '$extensions': {
        mode: {
          light: '#ffffff',
          dark: '#f0f6fc',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.white',
    '$type': 'color',
    '$value': '#ffffff',
    '$extensions': {
      mode: {
        light: '#ffffff',
        dark: '#f0f6fc',
      },
    },
  },
  'palette.gray0': {
    '_original': {
      '$value': '#f2f4f8',
      '$extensions': {
        mode: {
          light: '#f2f4f8',
          dark: '#f0f6fc',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray0',
    '$type': 'color',
    '$value': '#f2f4f8',
    '$extensions': {
      mode: {
        light: '#f2f4f8',
        dark: '#f0f6fc',
      },
    },
  },
  'palette.gray1': {
    '_original': {
      '$value': '#ECEFF4',
      '$extensions': {
        mode: {
          light: '#ECEFF4',
          dark: '#c9d1d9',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray1',
    '$type': 'color',
    '$value': '#eceff4',
    '$extensions': {
      mode: {
        light: '#eceff4',
        dark: '#c9d1d9',
      },
    },
  },
  'palette.gray2': {
    '_original': {
      '$value': '#E5E9F0',
      '$extensions': {
        mode: {
          light: '#E5E9F0',
          dark: '#b1bac4',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray2',
    '$type': 'color',
    '$value': '#e5e9f0',
    '$extensions': {
      mode: {
        light: '#e5e9f0',
        dark: '#b1bac4',
      },
    },
  },
  'palette.gray3': {
    '_original': {
      '$value': '#E5E9F0',
      '$extensions': {
        mode: {
          light: '#E5E9F0',
          dark: '#8b949e',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray3',
    '$type': 'color',
    '$value': '#e5e9f0',
    '$extensions': {
      mode: {
        light: '#e5e9f0',
        dark: '#8b949e',
      },
    },
  },
  'palette.gray4': {
    '_original': {
      '$value': '#afb8c1',
      '$extensions': {
        mode: {
          light: '#afb8c1',
          dark: '#6e7681',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray4',
    '$type': 'color',
    '$value': '#afb8c1',
    '$extensions': {
      mode: {
        light: '#afb8c1',
        dark: '#6e7681',
      },
    },
  },
  'palette.gray5': {
    '_original': {
      '$value': '#6e7781',
      '$extensions': {
        mode: {
          light: '#6e7781',
          dark: '#484f58',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray5',
    '$type': 'color',
    '$value': '#6e7781',
    '$extensions': {
      mode: {
        light: '#6e7781',
        dark: '#484f58',
      },
    },
  },
  'palette.gray6': {
    '_original': {
      '$value': '#4C566A',
      '$extensions': {
        mode: {
          light: '#4C566A',
          dark: '#30363d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray6',
    '$type': 'color',
    '$value': '#4c566a',
    '$extensions': {
      mode: {
        light: '#4c566a',
        dark: '#30363d',
      },
    },
  },
  'palette.gray7': {
    '_original': {
      '$value': '#434C5E',
      '$extensions': {
        mode: {
          light: '#434C5E',
          dark: '#21262d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray7',
    '$type': 'color',
    '$value': '#434c5e',
    '$extensions': {
      mode: {
        light: '#434c5e',
        dark: '#21262d',
      },
    },
  },
  'palette.gray8': {
    '_original': {
      '$value': '#434C5E',
      '$extensions': {
        mode: {
          light: '#434C5E',
          dark: '#161b22',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray8',
    '$type': 'color',
    '$value': '#434c5e',
    '$extensions': {
      mode: {
        light: '#434c5e',
        dark: '#161b22',
      },
    },
  },
  'palette.gray9': {
    '_original': {
      '$value': '#2E3440',
      '$extensions': {
        mode: {
          light: '#2E3440',
          dark: '#0d1117',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.gray9',
    '$type': 'color',
    '$value': '#2e3440',
    '$extensions': {
      mode: {
        light: '#2e3440',
        dark: '#0d1117',
      },
    },
  },
  'palette.green0': {
    '_original': {
      '$value': '#dafbe1',
      '$extensions': {
        mode: {
          light: '#dafbe1',
          dark: '#aff5b4',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green0',
    '$type': 'color',
    '$value': '#dafbe1',
    '$extensions': {
      mode: {
        light: '#dafbe1',
        dark: '#aff5b4',
      },
    },
  },
  'palette.green1': {
    '_original': {
      '$value': '#aceebb',
      '$extensions': {
        mode: {
          light: '#aceebb',
          dark: '#7ee787',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green1',
    '$type': 'color',
    '$value': '#aceebb',
    '$extensions': {
      mode: {
        light: '#aceebb',
        dark: '#7ee787',
      },
    },
  },
  'palette.green2': {
    '_original': {
      '$value': '#6fdd8b',
      '$extensions': {
        mode: {
          light: '#6fdd8b',
          dark: '#56d364',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green2',
    '$type': 'color',
    '$value': '#6fdd8b',
    '$extensions': {
      mode: {
        light: '#6fdd8b',
        dark: '#56d364',
      },
    },
  },
  'palette.green3': {
    '_original': {
      '$value': '#4ac26b',
      '$extensions': {
        mode: {
          light: '#4ac26b',
          dark: '#3fb950',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green3',
    '$type': 'color',
    '$value': '#4ac26b',
    '$extensions': {
      mode: {
        light: '#4ac26b',
        dark: '#3fb950',
      },
    },
  },
  'palette.green4': {
    '_original': {
      '$value': '#2da44e',
      '$extensions': {
        mode: {
          light: '#2da44e',
          dark: '#2ea043',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green4',
    '$type': 'color',
    '$value': '#2da44e',
    '$extensions': {
      mode: {
        light: '#2da44e',
        dark: '#2ea043',
      },
    },
  },
  'palette.green5': {
    '_original': {
      '$value': '#1a7f37',
      '$extensions': {
        mode: {
          light: '#1a7f37',
          dark: '#238636',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green5',
    '$type': 'color',
    '$value': '#1a7f37',
    '$extensions': {
      mode: {
        light: '#1a7f37',
        dark: '#238636',
      },
    },
  },
  'palette.green6': {
    '_original': {
      '$value': '#116329',
      '$extensions': {
        mode: {
          light: '#116329',
          dark: '#196c2e',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green6',
    '$type': 'color',
    '$value': '#116329',
    '$extensions': {
      mode: {
        light: '#116329',
        dark: '#196c2e',
      },
    },
  },
  'palette.green7': {
    '_original': {
      '$value': '#044f1e',
      '$extensions': {
        mode: {
          light: '#044f1e',
          dark: '#0f5323',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green7',
    '$type': 'color',
    '$value': '#044f1e',
    '$extensions': {
      mode: {
        light: '#044f1e',
        dark: '#0f5323',
      },
    },
  },
  'palette.green8': {
    '_original': {
      '$value': '#003d16',
      '$extensions': {
        mode: {
          light: '#003d16',
          dark: '#033a16',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green8',
    '$type': 'color',
    '$value': '#003d16',
    '$extensions': {
      mode: {
        light: '#003d16',
        dark: '#033a16',
      },
    },
  },
  'palette.green9': {
    '_original': {
      '$value': '#002d11',
      '$extensions': {
        mode: {
          light: '#002d11',
          dark: '#04260f',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.green9',
    '$type': 'color',
    '$value': '#002d11',
    '$extensions': {
      mode: {
        light: '#002d11',
        dark: '#04260f',
      },
    },
  },
  'palette.blue0': {
    '_original': {
      '$value': '#ddf4ff',
      '$extensions': {
        mode: {
          light: '#ddf4ff',
          dark: '#cae8ff',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue0',
    '$type': 'color',
    '$value': '#ddf4ff',
    '$extensions': {
      mode: {
        light: '#ddf4ff',
        dark: '#cae8ff',
      },
    },
  },
  'palette.blue1': {
    '_original': {
      '$value': '#b6e3ff',
      '$extensions': {
        mode: {
          light: '#b6e3ff',
          dark: '#a5d6ff',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue1',
    '$type': 'color',
    '$value': '#b6e3ff',
    '$extensions': {
      mode: {
        light: '#b6e3ff',
        dark: '#a5d6ff',
      },
    },
  },
  'palette.blue2': {
    '_original': {
      '$value': '#80ccff',
      '$extensions': {
        mode: {
          light: '#80ccff',
          dark: '#79c0ff',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue2',
    '$type': 'color',
    '$value': '#80ccff',
    '$extensions': {
      mode: {
        light: '#80ccff',
        dark: '#79c0ff',
      },
    },
  },
  'palette.blue3': {
    '_original': {
      '$value': '#54aeff',
      '$extensions': {
        mode: {
          light: '#54aeff',
          dark: '#58a6ff',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue3',
    '$type': 'color',
    '$value': '#54aeff',
    '$extensions': {
      mode: {
        light: '#54aeff',
        dark: '#58a6ff',
      },
    },
  },
  'palette.blue4': {
    '_original': {
      '$value': '#218bff',
      '$extensions': {
        mode: {
          light: '#218bff',
          dark: '#388bfd',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue4',
    '$type': 'color',
    '$value': '#218bff',
    '$extensions': {
      mode: {
        light: '#218bff',
        dark: '#388bfd',
      },
    },
  },
  'palette.blue5': {
    '_original': {
      '$value': '#0969da',
      '$extensions': {
        mode: {
          light: '#0969da',
          dark: '#1f6feb',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue5',
    '$type': 'color',
    '$value': '#0969da',
    '$extensions': {
      mode: {
        light: '#0969da',
        dark: '#1f6feb',
      },
    },
  },
  'palette.blue6': {
    '_original': {
      '$value': '#0550ae',
      '$extensions': {
        mode: {
          light: '#0550ae',
          dark: '#1158c7',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue6',
    '$type': 'color',
    '$value': '#0550ae',
    '$extensions': {
      mode: {
        light: '#0550ae',
        dark: '#1158c7',
      },
    },
  },
  'palette.blue7': {
    '_original': {
      '$value': '#033d8b',
      '$extensions': {
        mode: {
          light: '#033d8b',
          dark: '#0d419d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue7',
    '$type': 'color',
    '$value': '#033d8b',
    '$extensions': {
      mode: {
        light: '#033d8b',
        dark: '#0d419d',
      },
    },
  },
  'palette.blue8': {
    '_original': {
      '$value': '#0a3069',
      '$extensions': {
        mode: {
          light: '#0a3069',
          dark: '#0c2d6b',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue8',
    '$type': 'color',
    '$value': '#0a3069',
    '$extensions': {
      mode: {
        light: '#0a3069',
        dark: '#0c2d6b',
      },
    },
  },
  'palette.blue9': {
    '_original': {
      '$value': '#002155',
      '$extensions': {
        mode: {
          light: '#002155',
          dark: '#051d4d',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.blue9',
    '$type': 'color',
    '$value': '#002155',
    '$extensions': {
      mode: {
        light: '#002155',
        dark: '#051d4d',
      },
    },
  },
  'palette.coral0': {
    '_original': {
      '$value': '#FFF0EB',
      '$extensions': {
        mode: {
          light: '#FFF0EB',
          dark: '#FFDDD2',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral0',
    '$type': 'color',
    '$value': '#fff0eb',
    '$extensions': {
      mode: {
        light: '#fff0eb',
        dark: '#ffddd2',
      },
    },
  },
  'palette.coral1': {
    '_original': {
      '$value': '#FFD6CC',
      '$extensions': {
        mode: {
          light: '#FFD6CC',
          dark: '#FFC2B2',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral1',
    '$type': 'color',
    '$value': '#ffd6cc',
    '$extensions': {
      mode: {
        light: '#ffd6cc',
        dark: '#ffc2b2',
      },
    },
  },
  'palette.coral2': {
    '_original': {
      '$value': '#FFB4A1',
      '$extensions': {
        mode: {
          light: '#FFB4A1',
          dark: '#FFA28B',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral2',
    '$type': 'color',
    '$value': '#ffb4a1',
    '$extensions': {
      mode: {
        light: '#ffb4a1',
        dark: '#ffa28b',
      },
    },
  },
  'palette.coral3': {
    '_original': {
      '$value': '#FD8C73',
      '$extensions': {
        mode: {
          light: '#FD8C73',
          dark: '#F78166',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral3',
    '$type': 'color',
    '$value': '#fd8c73',
    '$extensions': {
      mode: {
        light: '#fd8c73',
        dark: '#f78166',
      },
    },
  },
  'palette.coral4': {
    '_original': {
      '$value': '#EC6547',
      '$extensions': {
        mode: {
          light: '#EC6547',
          dark: '#EA6045',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral4',
    '$type': 'color',
    '$value': '#ec6547',
    '$extensions': {
      mode: {
        light: '#ec6547',
        dark: '#ea6045',
      },
    },
  },
  'palette.coral5': {
    '_original': {
      '$value': '#C4432B',
      '$extensions': {
        mode: {
          light: '#C4432B',
          dark: '#CF462D',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral5',
    '$type': 'color',
    '$value': '#c4432b',
    '$extensions': {
      mode: {
        light: '#c4432b',
        dark: '#cf462d',
      },
    },
  },
  'palette.coral6': {
    '_original': {
      '$value': '#9E2F1C',
      '$extensions': {
        mode: {
          light: '#9E2F1C',
          dark: '#AC3220',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral6',
    '$type': 'color',
    '$value': '#9e2f1c',
    '$extensions': {
      mode: {
        light: '#9e2f1c',
        dark: '#ac3220',
      },
    },
  },
  'palette.coral7': {
    '_original': {
      '$value': '#801F0F',
      '$extensions': {
        mode: {
          light: '#801F0F',
          dark: '#872012',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral7',
    '$type': 'color',
    '$value': '#801f0f',
    '$extensions': {
      mode: {
        light: '#801f0f',
        dark: '#872012',
      },
    },
  },
  'palette.coral8': {
    '_original': {
      '$value': '#691105',
      '$extensions': {
        mode: {
          light: '#691105',
          dark: '#640D04',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral8',
    '$type': 'color',
    '$value': '#691105',
    '$extensions': {
      mode: {
        light: '#691105',
        dark: '#640d04',
      },
    },
  },
  'palette.coral9': {
    '_original': {
      '$value': '#510901',
      '$extensions': {
        mode: {
          light: '#510901',
          dark: '#460701',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.coral9',
    '$type': 'color',
    '$value': '#510901',
    '$extensions': {
      mode: {
        light: '#510901',
        dark: '#460701',
      },
    },
  },
  'palette.red0': {
    '_original': {
      '$value': '#FFEBE9',
      '$extensions': {
        mode: {
          light: '#FFEBE9',
          dark: '#ffdcd7',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red0',
    '$type': 'color',
    '$value': '#ffebe9',
    '$extensions': {
      mode: {
        light: '#ffebe9',
        dark: '#ffdcd7',
      },
    },
  },
  'palette.red1': {
    '_original': {
      '$value': '#ffcecb',
      '$extensions': {
        mode: {
          light: '#ffcecb',
          dark: '#ffc1ba',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red1',
    '$type': 'color',
    '$value': '#ffcecb',
    '$extensions': {
      mode: {
        light: '#ffcecb',
        dark: '#ffc1ba',
      },
    },
  },
  'palette.red2': {
    '_original': {
      '$value': '#ffaba8',
      '$extensions': {
        mode: {
          light: '#ffaba8',
          dark: '#ffa198',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red2',
    '$type': 'color',
    '$value': '#ffaba8',
    '$extensions': {
      mode: {
        light: '#ffaba8',
        dark: '#ffa198',
      },
    },
  },
  'palette.red3': {
    '_original': {
      '$value': '#ff8182',
      '$extensions': {
        mode: {
          light: '#ff8182',
          dark: '#ff7b72',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red3',
    '$type': 'color',
    '$value': '#ff8182',
    '$extensions': {
      mode: {
        light: '#ff8182',
        dark: '#ff7b72',
      },
    },
  },
  'palette.red4': {
    '_original': {
      '$value': '#fa4549',
      '$extensions': {
        mode: {
          light: '#fa4549',
          dark: '#f85149',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red4',
    '$type': 'color',
    '$value': '#fa4549',
    '$extensions': {
      mode: {
        light: '#fa4549',
        dark: '#f85149',
      },
    },
  },
  'palette.red5': {
    '_original': {
      '$value': '#cf222e',
      '$extensions': {
        mode: {
          light: '#cf222e',
          dark: '#da3633',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red5',
    '$type': 'color',
    '$value': '#cf222e',
    '$extensions': {
      mode: {
        light: '#cf222e',
        dark: '#da3633',
      },
    },
  },
  'palette.red6': {
    '_original': {
      '$value': '#a40e26',
      '$extensions': {
        mode: {
          light: '#a40e26',
          dark: '#b62324',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red6',
    '$type': 'color',
    '$value': '#a40e26',
    '$extensions': {
      mode: {
        light: '#a40e26',
        dark: '#b62324',
      },
    },
  },
  'palette.red7': {
    '_original': {
      '$value': '#82071e',
      '$extensions': {
        mode: {
          light: '#82071e',
          dark: '#8e1519',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red7',
    '$type': 'color',
    '$value': '#82071e',
    '$extensions': {
      mode: {
        light: '#82071e',
        dark: '#8e1519',
      },
    },
  },
  'palette.red8': {
    '_original': {
      '$value': '#660018',
      '$extensions': {
        mode: {
          light: '#660018',
          dark: '#67060c',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red8',
    '$type': 'color',
    '$value': '#660018',
    '$extensions': {
      mode: {
        light: '#660018',
        dark: '#67060c',
      },
    },
  },
  'palette.red9': {
    '_original': {
      '$value': '#4c0014',
      '$extensions': {
        mode: {
          light: '#4c0014',
          dark: '#490202',
        },
      },
    },
    '_group': {
      id: 'palette',
      '$extensions': {
        requiredModes: [],
        modes: ['light', 'dark'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'palette.red9',
    '$type': 'color',
    '$value': '#4c0014',
    '$extensions': {
      mode: {
        light: '#4c0014',
        dark: '#490202',
      },
    },
  },
  'color.background': {
    '_original': {
      '$value': '{palette.gray0}',
    },
    '_group': {
      id: 'color',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.background',
    '$type': 'color',
    '$value': '#f2f4f8',
  },
  'color.text.body': {
    '_original': {
      '$value': '{palette.black}',
    },
    '_group': {
      id: 'color.text',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.text.body',
    '$type': 'color',
    '$value': '#1d2129',
  },
  'color.text.muted': {
    '_original': {
      '$value': '{palette.gray5}',
    },
    '_group': {
      id: 'color.text',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.text.muted',
    '$type': 'color',
    '$value': '#6e7781',
  },
  'color.text.error': {
    '_original': {
      '$value': '{palette.red7}',
    },
    '_group': {
      id: 'color.text',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.text.error',
    '$type': 'color',
    '$value': '#82071e',
  },
  'color.text.link': {
    '_original': {
      '$value': '{palette.blue5}',
    },
    '_group': {
      id: 'color.text',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.text.link',
    '$type': 'color',
    '$value': '#0969da',
  },
  'color.border.muted': {
    '_original': {
      '$value': '{palette.gray1}',
    },
    '_group': {
      id: 'color.border',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'color',
    },
    id: 'color.border.muted',
    '$type': 'color',
    '$value': '#eceff4',
  },
  'spacing.spacer0': {
    '_original': {
      '$value': '0px',
    },
    '_group': {
      id: 'spacing',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacer0',
    '$type': 'dimension',
    '$value': '0',
  },
  'spacing.spacerXs': {
    '_original': {
      '$value': '4px',
    },
    '_group': {
      id: 'spacing',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacerXs',
    '$type': 'dimension',
    '$value': '4px',
  },
  'spacing.spacerS': {
    '_original': {
      '$value': '8px',
    },
    '_group': {
      id: 'spacing',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacerS',
    '$type': 'dimension',
    '$value': '8px',
  },
  'spacing.spacerM': {
    '_original': {
      '$value': '16px',
    },
    '_group': {
      id: 'spacing',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacerM',
    '$type': 'dimension',
    '$value': '16px',
  },
  'spacing.spacerX': {
    '_original': {
      '$value': '24px',
    },
    '_group': {
      id: 'spacing',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacerX',
    '$type': 'dimension',
    '$value': '24px',
  },
  'spacing.spacerXl': {
    '_original': {
      '$value': '32px',
    },
    '_group': {
      id: 'spacing',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacerXl',
    '$type': 'dimension',
    '$value': '32px',
  },
  'spacing.spacerXxl': {
    '_original': {
      '$value': '40px',
    },
    '_group': {
      id: 'spacing',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'spacing.spacerXxl',
    '$type': 'dimension',
    '$value': '40px',
  },
  'shadow.sm': {
    '_original': {
      '$value': {
        offsetX: '0px',
        offsetY: '8px',
        blur: '16px',
        spread: '0px',
        color: 'rgba(100, 100, 111, 0.2)',
      },
    },
    '_group': {
      id: 'shadow',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'shadow',
    },
    id: 'shadow.sm',
    '$type': 'shadow',
    '$value': {
      offsetX: '0',
      offsetY: '8px',
      blur: '16px',
      spread: '0',
      color: '#64646f33',
    },
  },
  'shadow.md': {
    '_original': {
      '$value': {
        offsetX: '0px',
        offsetY: '12px',
        blur: '24px',
        spread: '0px',
        color: 'rgba(100, 100, 111, 0.2)',
      },
    },
    '_group': {
      id: 'shadow',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'shadow',
    },
    id: 'shadow.md',
    '$type': 'shadow',
    '$value': {
      offsetX: '0',
      offsetY: '12px',
      blur: '24px',
      spread: '0',
      color: '#64646f33',
    },
  },
  'shadow.lg': {
    '_original': {
      '$value': {
        offsetX: '0px',
        offsetY: '16px',
        blur: '30px',
        spread: '0px',
        color: 'rgba(100, 100, 111, 0.2)',
      },
    },
    '_group': {
      id: 'shadow',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'shadow',
    },
    id: 'shadow.lg',
    '$type': 'shadow',
    '$value': {
      offsetX: '0',
      offsetY: '16px',
      blur: '30px',
      spread: '0',
      color: '#64646f33',
    },
  },
  'font.family.system': {
    '_original': {
      '$value': ['-apple-system,', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
    },
    '_group': {
      id: 'font.family',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'font',
    },
    id: 'font.family.system',
    '$type': 'font',
    '$value': ['-apple-system,', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
  },
  'font.family.monospace': {
    '_original': {
      '$value': ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'Courier', 'monospace'],
    },
    '_group': {
      id: 'font.family',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'font',
    },
    id: 'font.family.monospace',
    '$type': 'font',
    '$value': ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'Courier', 'monospace'],
  },
  'font.family.display': {
    '_original': {
      '$value': ['InterUI', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Segoe UI', 'Oxygen', 'Ubuntu', 'Cantarell', 'Open Sans', 'sans-serif'],
    },
    '_group': {
      id: 'font.family',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'font',
    },
    id: 'font.family.display',
    '$type': 'font',
    '$value': ['InterUI', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Segoe UI', 'Oxygen', 'Ubuntu', 'Cantarell', 'Open Sans', 'sans-serif'],
  },
  'font.family.size.f00': {
    '_original': {
      '$value': '32px',
      '$extensions': {
        mode: {
          mobile: '32px',
          desktop: '48px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f00',
    '$type': 'dimension',
    '$value': '32px',
    '$extensions': {
      mode: {
        mobile: '32px',
        desktop: '48px',
      },
    },
  },
  'font.family.size.f0': {
    '_original': {
      '$value': '32px',
      '$extensions': {
        mode: {
          mobile: '32px',
          desktop: '40px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f0',
    '$type': 'dimension',
    '$value': '32px',
    '$extensions': {
      mode: {
        mobile: '32px',
        desktop: '40px',
      },
    },
  },
  'font.family.size.f1': {
    '_original': {
      '$value': '26px',
      '$extensions': {
        mode: {
          mobile: '26px',
          desktop: '32px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f1',
    '$type': 'dimension',
    '$value': '26px',
    '$extensions': {
      mode: {
        mobile: '26px',
        desktop: '32px',
      },
    },
  },
  'font.family.size.f2': {
    '_original': {
      '$value': '22px',
      '$extensions': {
        mode: {
          mobile: '22px',
          desktop: '24px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f2',
    '$type': 'dimension',
    '$value': '22px',
    '$extensions': {
      mode: {
        mobile: '22px',
        desktop: '24px',
      },
    },
  },
  'font.family.size.f3': {
    '_original': {
      '$value': '16px',
      '$extensions': {
        mode: {
          mobile: '16px',
          desktop: '20px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f3',
    '$type': 'dimension',
    '$value': '16px',
    '$extensions': {
      mode: {
        mobile: '16px',
        desktop: '20px',
      },
    },
  },
  'font.family.size.f4': {
    '_original': {
      '$value': '16px',
      '$extensions': {
        mode: {
          mobile: '16px',
          desktop: '16px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f4',
    '$type': 'dimension',
    '$value': '16px',
    '$extensions': {
      mode: {
        mobile: '16px',
        desktop: '16px',
      },
    },
  },
  'font.family.size.f5': {
    '_original': {
      '$value': '14px',
      '$extensions': {
        mode: {
          mobile: '14px',
          desktop: '14px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f5',
    '$type': 'dimension',
    '$value': '14px',
    '$extensions': {
      mode: {
        mobile: '14px',
        desktop: '14px',
      },
    },
  },
  'font.family.size.f6': {
    '_original': {
      '$value': '12px',
      '$extensions': {
        mode: {
          mobile: '12px',
          desktop: '12px',
        },
      },
    },
    '_group': {
      id: 'font.family.size',
      '$extensions': {
        requiredModes: [],
        modes: ['mobile', 'desktop'],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.size.f6',
    '$type': 'dimension',
    '$value': '12px',
    '$extensions': {
      mode: {
        mobile: '12px',
        desktop: '12px',
      },
    },
  },
  'font.family.lineHeight.default': {
    '_original': {
      '$value': '1.5',
    },
    '_group': {
      id: 'font.family.lineHeight',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.lineHeight.default',
    '$type': 'dimension',
    '$value': '1.5',
  },
  'font.family.lineHeight.condensed': {
    '_original': {
      '$value': '1.25',
    },
    '_group': {
      id: 'font.family.lineHeight',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.lineHeight.condensed',
    '$type': 'dimension',
    '$value': '1.25',
  },
  'font.family.lineHeight.condensedUltra': {
    '_original': {
      '$value': '1',
    },
    '_group': {
      id: 'font.family.lineHeight',
      '$extensions': {
        requiredModes: [],
      },
      '$name': 'NosEditor themes',
      '$description': 'design tokens for noseditor',
      '$type': 'dimension',
    },
    id: 'font.family.lineHeight.condensedUltra',
    '$type': 'dimension',
    '$value': '1',
  },
};

export const modes = {
  'palette.black': {
    light: '#1d2129',
    dark: '#010409',
  },
  'palette.white': {
    light: '#ffffff',
    dark: '#f0f6fc',
  },
  'palette.gray0': {
    light: '#f2f4f8',
    dark: '#f0f6fc',
  },
  'palette.gray1': {
    light: '#eceff4',
    dark: '#c9d1d9',
  },
  'palette.gray2': {
    light: '#e5e9f0',
    dark: '#b1bac4',
  },
  'palette.gray3': {
    light: '#e5e9f0',
    dark: '#8b949e',
  },
  'palette.gray4': {
    light: '#afb8c1',
    dark: '#6e7681',
  },
  'palette.gray5': {
    light: '#6e7781',
    dark: '#484f58',
  },
  'palette.gray6': {
    light: '#4c566a',
    dark: '#30363d',
  },
  'palette.gray7': {
    light: '#434c5e',
    dark: '#21262d',
  },
  'palette.gray8': {
    light: '#434c5e',
    dark: '#161b22',
  },
  'palette.gray9': {
    light: '#2e3440',
    dark: '#0d1117',
  },
  'palette.green0': {
    light: '#dafbe1',
    dark: '#aff5b4',
  },
  'palette.green1': {
    light: '#aceebb',
    dark: '#7ee787',
  },
  'palette.green2': {
    light: '#6fdd8b',
    dark: '#56d364',
  },
  'palette.green3': {
    light: '#4ac26b',
    dark: '#3fb950',
  },
  'palette.green4': {
    light: '#2da44e',
    dark: '#2ea043',
  },
  'palette.green5': {
    light: '#1a7f37',
    dark: '#238636',
  },
  'palette.green6': {
    light: '#116329',
    dark: '#196c2e',
  },
  'palette.green7': {
    light: '#044f1e',
    dark: '#0f5323',
  },
  'palette.green8': {
    light: '#003d16',
    dark: '#033a16',
  },
  'palette.green9': {
    light: '#002d11',
    dark: '#04260f',
  },
  'palette.blue0': {
    light: '#ddf4ff',
    dark: '#cae8ff',
  },
  'palette.blue1': {
    light: '#b6e3ff',
    dark: '#a5d6ff',
  },
  'palette.blue2': {
    light: '#80ccff',
    dark: '#79c0ff',
  },
  'palette.blue3': {
    light: '#54aeff',
    dark: '#58a6ff',
  },
  'palette.blue4': {
    light: '#218bff',
    dark: '#388bfd',
  },
  'palette.blue5': {
    light: '#0969da',
    dark: '#1f6feb',
  },
  'palette.blue6': {
    light: '#0550ae',
    dark: '#1158c7',
  },
  'palette.blue7': {
    light: '#033d8b',
    dark: '#0d419d',
  },
  'palette.blue8': {
    light: '#0a3069',
    dark: '#0c2d6b',
  },
  'palette.blue9': {
    light: '#002155',
    dark: '#051d4d',
  },
  'palette.coral0': {
    light: '#fff0eb',
    dark: '#ffddd2',
  },
  'palette.coral1': {
    light: '#ffd6cc',
    dark: '#ffc2b2',
  },
  'palette.coral2': {
    light: '#ffb4a1',
    dark: '#ffa28b',
  },
  'palette.coral3': {
    light: '#fd8c73',
    dark: '#f78166',
  },
  'palette.coral4': {
    light: '#ec6547',
    dark: '#ea6045',
  },
  'palette.coral5': {
    light: '#c4432b',
    dark: '#cf462d',
  },
  'palette.coral6': {
    light: '#9e2f1c',
    dark: '#ac3220',
  },
  'palette.coral7': {
    light: '#801f0f',
    dark: '#872012',
  },
  'palette.coral8': {
    light: '#691105',
    dark: '#640d04',
  },
  'palette.coral9': {
    light: '#510901',
    dark: '#460701',
  },
  'palette.red0': {
    light: '#ffebe9',
    dark: '#ffdcd7',
  },
  'palette.red1': {
    light: '#ffcecb',
    dark: '#ffc1ba',
  },
  'palette.red2': {
    light: '#ffaba8',
    dark: '#ffa198',
  },
  'palette.red3': {
    light: '#ff8182',
    dark: '#ff7b72',
  },
  'palette.red4': {
    light: '#fa4549',
    dark: '#f85149',
  },
  'palette.red5': {
    light: '#cf222e',
    dark: '#da3633',
  },
  'palette.red6': {
    light: '#a40e26',
    dark: '#b62324',
  },
  'palette.red7': {
    light: '#82071e',
    dark: '#8e1519',
  },
  'palette.red8': {
    light: '#660018',
    dark: '#67060c',
  },
  'palette.red9': {
    light: '#4c0014',
    dark: '#490202',
  },
  'font.family.size.f00': {
    mobile: '32px',
    desktop: '48px',
  },
  'font.family.size.f0': {
    mobile: '32px',
    desktop: '40px',
  },
  'font.family.size.f1': {
    mobile: '26px',
    desktop: '32px',
  },
  'font.family.size.f2': {
    mobile: '22px',
    desktop: '24px',
  },
  'font.family.size.f3': {
    mobile: '16px',
    desktop: '20px',
  },
  'font.family.size.f4': {
    mobile: '16px',
    desktop: '16px',
  },
  'font.family.size.f5': {
    mobile: '14px',
    desktop: '14px',
  },
  'font.family.size.f6': {
    mobile: '12px',
    desktop: '12px',
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
