
/**
 * Design Tokens
 * Autogenerated from npm run build:design-tokens.
 * use with same-name.css.
 * DO NOT EDIT!
 */
export const themed = {
  palette: {
    black: 'var(--nos-palette-black)',
    white: 'var(--nos-palette-white)',
    gray0: 'var(--nos-palette-gray0)',
    gray1: 'var(--nos-palette-gray1)',
    gray2: 'var(--nos-palette-gray2)',
    gray3: 'var(--nos-palette-gray3)',
    gray4: 'var(--nos-palette-gray4)',
    gray5: 'var(--nos-palette-gray5)',
    gray6: 'var(--nos-palette-gray6)',
    gray7: 'var(--nos-palette-gray7)',
    gray8: 'var(--nos-palette-gray8)',
    gray9: 'var(--nos-palette-gray9)',
    green0: 'var(--nos-palette-green0)',
    green1: 'var(--nos-palette-green1)',
    green2: 'var(--nos-palette-green2)',
    green3: 'var(--nos-palette-green3)',
    green4: 'var(--nos-palette-green4)',
    green5: 'var(--nos-palette-green5)',
    green6: 'var(--nos-palette-green6)',
    green7: 'var(--nos-palette-green7)',
    green8: 'var(--nos-palette-green8)',
    green9: 'var(--nos-palette-green9)',
    blue0: 'var(--nos-palette-blue0)',
    blue1: 'var(--nos-palette-blue1)',
    blue2: 'var(--nos-palette-blue2)',
    blue3: 'var(--nos-palette-blue3)',
    blue4: 'var(--nos-palette-blue4)',
    blue5: 'var(--nos-palette-blue5)',
    blue6: 'var(--nos-palette-blue6)',
    blue7: 'var(--nos-palette-blue7)',
    blue8: 'var(--nos-palette-blue8)',
    blue9: 'var(--nos-palette-blue9)',
    coral0: 'var(--nos-palette-coral0)',
    coral1: 'var(--nos-palette-coral1)',
    coral2: 'var(--nos-palette-coral2)',
    coral3: 'var(--nos-palette-coral3)',
    coral4: 'var(--nos-palette-coral4)',
    coral5: 'var(--nos-palette-coral5)',
    coral6: 'var(--nos-palette-coral6)',
    coral7: 'var(--nos-palette-coral7)',
    coral8: 'var(--nos-palette-coral8)',
    coral9: 'var(--nos-palette-coral9)',
    red0: 'var(--nos-palette-red0)',
    red1: 'var(--nos-palette-red1)',
    red2: 'var(--nos-palette-red2)',
    red3: 'var(--nos-palette-red3)',
    red4: 'var(--nos-palette-red4)',
    red5: 'var(--nos-palette-red5)',
    red6: 'var(--nos-palette-red6)',
    red7: 'var(--nos-palette-red7)',
    red8: 'var(--nos-palette-red8)',
    red9: 'var(--nos-palette-red9)'
  },
  color: {
    background: 'var(--nos-color-background)',
    text: {
      body: 'var(--nos-color-text-body)',
      muted: 'var(--nos-color-text-muted)',
      error: 'var(--nos-color-text-error)',
      link: 'var(--nos-color-text-link)'
    },
    border: {
      light: 'var(--nos-color-border-light)',
      muted: 'var(--nos-color-border-muted)'
    }
  },
  spacing: {
    spacer0: 'var(--nos-spacing-spacer0)',
    spacerXs: 'var(--nos-spacing-spacerXs)',
    spacerS: 'var(--nos-spacing-spacerS)',
    spacerM: 'var(--nos-spacing-spacerM)',
    spacerX: 'var(--nos-spacing-spacerX)',
    spacerXl: 'var(--nos-spacing-spacerXl)',
    spacerXxl: 'var(--nos-spacing-spacerXxl)'
  },
  size: {
    borderRadius: {
      xs: 'var(--nos-size-borderRadius-xs)',
      sm: 'var(--nos-size-borderRadius-sm)',
      md: 'var(--nos-size-borderRadius-md)',
      lg: 'var(--nos-size-borderRadius-lg)',
      xl: 'var(--nos-size-borderRadius-xl)'
    }
  },
  shadow: {
    sm: 'var(--nos-shadow-sm)',
    md: 'var(--nos-shadow-md)',
    lg: 'var(--nos-shadow-lg)'
  },
  font: {
    family: {
      system: 'var(--nos-font-family-system)',
      monospace: 'var(--nos-font-family-monospace)',
      display: 'var(--nos-font-family-display)',
      size: {
        f00: 'var(--nos-font-family-size-f00)',
        f0: 'var(--nos-font-family-size-f0)',
        f1: 'var(--nos-font-family-size-f1)',
        f2: 'var(--nos-font-family-size-f2)',
        f3: 'var(--nos-font-family-size-f3)',
        f4: 'var(--nos-font-family-size-f4)',
        f5: 'var(--nos-font-family-size-f5)',
        f6: 'var(--nos-font-family-size-f6)'
      },
      lineHeight: {
        xs: 'var(--nos-font-family-lineHeight-xs)',
        sm: 'var(--nos-font-family-lineHeight-sm)',
        md: 'var(--nos-font-family-lineHeight-md)',
        default: 'var(--nos-font-family-lineHeight-default)',
        lg: 'var(--nos-font-family-lineHeight-lg)',
        xl: 'var(--nos-font-family-lineHeight-xl)'
      }
    }
  }
} as const;