// 一些全局通用action

// settings
export const RESET_TO_DEFAULT_LAYOUT = 'RESET_TO_DEFAULT_LAYOUT';
export const LOGO_BG = 'LOGO_BG';
export const NAVBAR_BG = 'NAVBAR_BG';
export const SIDEBAR_BG = 'SIDEBAR_BG';
export const THEME = 'THEME';
export const DIRECTION = 'DIRECTION';
export const SIDEBAR_POSITION = 'SIDEBAR_POSITION';
export const HEADER_POSITION = 'HEADER_POSITION';
export const LAYOUT = 'LAYOUT';
export const SIDEBAR_TYPE = 'SIDEBAR_TYPE';
export const SIDE_PANEL_TYPE = 'SIDE_PANEL_TYPE';
export const SIDE_PANEL_POSITION = 'SIDE_PANEL_POSITION';
export const SIDEBAR_VISIBLE_MODE = 'SIDEBAR_VISIBLE_MODE';
export const TOGGLE_SIDE_PANEL = 'TOGGLE_SIDE_PANEL';
export const TOGGLE_SETTINGS_COG_BUTTON = 'TOGGLE_SETTINGS_COG_BUTTON';

// auth
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOAD_USER = 'LOAD_USER';
export const AUTHENTICATE_START = 'AUTHENTICATE_START';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const AUTHENTICATE_FALSE = 'AUTHENTICATE_FALSE';
