/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

import {
  type BorderToken,
  type ColorToken,
  type CubicBezierToken,
  type DimensionToken,
  type DurationToken,
  type FontFamilyToken,
  type FontWeightToken,
  type NumberToken,
  type ParsedBorderToken,
  type ParsedColorToken,
  type ParsedCubicBezierToken,
  type ParsedDimensionToken,
  type ParsedDurationToken,
  type ParsedFontFamilyToken,
  type ParsedFontWeightToken,
  type ParsedNumberToken,
  type ParsedShadowToken,
  type ParsedTypographyToken,
  type ShadowToken,
  type TypographyToken,
} from '@cobalt-ui/core';

export declare const tokens: {
  'palette.black': ColorToken['$value'];
  'palette.white': ColorToken['$value'];
  'palette.gray25': ColorToken['$value'];
  'palette.gray50': ColorToken['$value'];
  'palette.gray100': ColorToken['$value'];
  'palette.gray200': ColorToken['$value'];
  'palette.gray300': ColorToken['$value'];
  'palette.gray400': ColorToken['$value'];
  'palette.gray500': ColorToken['$value'];
  'palette.gray600': ColorToken['$value'];
  'palette.gray700': ColorToken['$value'];
  'palette.gray800': ColorToken['$value'];
  'palette.gray900': ColorToken['$value'];
  'palette.gray950': ColorToken['$value'];
  'palette.slate50': ColorToken['$value'];
  'palette.slate100': ColorToken['$value'];
  'palette.slate200': ColorToken['$value'];
  'palette.slate300': ColorToken['$value'];
  'palette.slate400': ColorToken['$value'];
  'palette.slate500': ColorToken['$value'];
  'palette.slate600': ColorToken['$value'];
  'palette.slate700': ColorToken['$value'];
  'palette.slate800': ColorToken['$value'];
  'palette.slate900': ColorToken['$value'];
  'palette.slate950': ColorToken['$value'];
  'palette.teal50': ColorToken['$value'];
  'palette.teal100': ColorToken['$value'];
  'palette.teal200': ColorToken['$value'];
  'palette.teal300': ColorToken['$value'];
  'palette.teal400': ColorToken['$value'];
  'palette.teal500': ColorToken['$value'];
  'palette.teal600': ColorToken['$value'];
  'palette.teal700': ColorToken['$value'];
  'palette.teal800': ColorToken['$value'];
  'palette.teal900': ColorToken['$value'];
  'palette.green50': ColorToken['$value'];
  'palette.green100': ColorToken['$value'];
  'palette.green200': ColorToken['$value'];
  'palette.green300': ColorToken['$value'];
  'palette.green400': ColorToken['$value'];
  'palette.green500': ColorToken['$value'];
  'palette.green600': ColorToken['$value'];
  'palette.green700': ColorToken['$value'];
  'palette.green800': ColorToken['$value'];
  'palette.green900': ColorToken['$value'];
  'palette.green950': ColorToken['$value'];
  'palette.blue50': ColorToken['$value'];
  'palette.blue100': ColorToken['$value'];
  'palette.blue200': ColorToken['$value'];
  'palette.blue300': ColorToken['$value'];
  'palette.blue400': ColorToken['$value'];
  'palette.blue500': ColorToken['$value'];
  'palette.blue600': ColorToken['$value'];
  'palette.blue700': ColorToken['$value'];
  'palette.blue800': ColorToken['$value'];
  'palette.blue900': ColorToken['$value'];
  'palette.blue950': ColorToken['$value'];
  'palette.cyan50': ColorToken['$value'];
  'palette.cyan100': ColorToken['$value'];
  'palette.cyan200': ColorToken['$value'];
  'palette.cyan300': ColorToken['$value'];
  'palette.cyan400': ColorToken['$value'];
  'palette.cyan500': ColorToken['$value'];
  'palette.cyan600': ColorToken['$value'];
  'palette.cyan700': ColorToken['$value'];
  'palette.cyan800': ColorToken['$value'];
  'palette.cyan900': ColorToken['$value'];
  'palette.cyan950': ColorToken['$value'];
  'palette.violet50': ColorToken['$value'];
  'palette.violet100': ColorToken['$value'];
  'palette.violet200': ColorToken['$value'];
  'palette.violet300': ColorToken['$value'];
  'palette.violet400': ColorToken['$value'];
  'palette.violet500': ColorToken['$value'];
  'palette.violet600': ColorToken['$value'];
  'palette.violet700': ColorToken['$value'];
  'palette.violet800': ColorToken['$value'];
  'palette.violet900': ColorToken['$value'];
  'palette.violet950': ColorToken['$value'];
  'palette.purple50': ColorToken['$value'];
  'palette.purple100': ColorToken['$value'];
  'palette.purple200': ColorToken['$value'];
  'palette.purple300': ColorToken['$value'];
  'palette.purple400': ColorToken['$value'];
  'palette.purple500': ColorToken['$value'];
  'palette.purple600': ColorToken['$value'];
  'palette.purple700': ColorToken['$value'];
  'palette.purple800': ColorToken['$value'];
  'palette.purple900': ColorToken['$value'];
  'palette.purple950': ColorToken['$value'];
  'palette.orange50': ColorToken['$value'];
  'palette.orange100': ColorToken['$value'];
  'palette.orange200': ColorToken['$value'];
  'palette.orange300': ColorToken['$value'];
  'palette.orange400': ColorToken['$value'];
  'palette.orange500': ColorToken['$value'];
  'palette.orange600': ColorToken['$value'];
  'palette.orange700': ColorToken['$value'];
  'palette.orange800': ColorToken['$value'];
  'palette.orange900': ColorToken['$value'];
  'palette.orange950': ColorToken['$value'];
  'palette.amber50': ColorToken['$value'];
  'palette.amber100': ColorToken['$value'];
  'palette.amber200': ColorToken['$value'];
  'palette.amber300': ColorToken['$value'];
  'palette.amber400': ColorToken['$value'];
  'palette.amber500': ColorToken['$value'];
  'palette.amber600': ColorToken['$value'];
  'palette.amber700': ColorToken['$value'];
  'palette.amber800': ColorToken['$value'];
  'palette.amber900': ColorToken['$value'];
  'palette.amber950': ColorToken['$value'];
  'palette.yellow50': ColorToken['$value'];
  'palette.yellow100': ColorToken['$value'];
  'palette.yellow200': ColorToken['$value'];
  'palette.yellow300': ColorToken['$value'];
  'palette.yellow400': ColorToken['$value'];
  'palette.yellow500': ColorToken['$value'];
  'palette.yellow600': ColorToken['$value'];
  'palette.yellow700': ColorToken['$value'];
  'palette.yellow800': ColorToken['$value'];
  'palette.yellow900': ColorToken['$value'];
  'palette.yellow950': ColorToken['$value'];
  'palette.red50': ColorToken['$value'];
  'palette.red100': ColorToken['$value'];
  'palette.red200': ColorToken['$value'];
  'palette.red300': ColorToken['$value'];
  'palette.red400': ColorToken['$value'];
  'palette.red500': ColorToken['$value'];
  'palette.red600': ColorToken['$value'];
  'palette.red700': ColorToken['$value'];
  'palette.red800': ColorToken['$value'];
  'palette.red900': ColorToken['$value'];
  'palette.red950': ColorToken['$value'];
  'palette.rose50': ColorToken['$value'];
  'palette.rose100': ColorToken['$value'];
  'palette.rose200': ColorToken['$value'];
  'palette.rose300': ColorToken['$value'];
  'palette.rose400': ColorToken['$value'];
  'palette.rose500': ColorToken['$value'];
  'palette.rose600': ColorToken['$value'];
  'palette.rose700': ColorToken['$value'];
  'palette.rose800': ColorToken['$value'];
  'palette.rose900': ColorToken['$value'];
  'palette.rose950': ColorToken['$value'];
  'color.brand.primary': ColorToken['$value'];
  'color.brand.light': ColorToken['$value'];
  'color.brand.lighter': ColorToken['$value'];
  'color.brand.dark': ColorToken['$value'];
  'color.brand.darker': ColorToken['$value'];
  'color.background.default': ColorToken['$value'];
  'color.background.hover': ColorToken['$value'];
  'color.background.dark': ColorToken['$value'];
  'color.text.body': ColorToken['$value'];
  'color.text.muted': ColorToken['$value'];
  'color.text.error': ColorToken['$value'];
  'color.text.link': ColorToken['$value'];
  'color.brightness.pct0': NumberToken['$value'];
  'color.brightness.pct50': NumberToken['$value'];
  'color.brightness.pct75': NumberToken['$value'];
  'color.brightness.pct90': NumberToken['$value'];
  'color.brightness.pct95': NumberToken['$value'];
  'color.brightness.pct100': NumberToken['$value'];
  'color.brightness.pct105': NumberToken['$value'];
  'color.brightness.pct110': NumberToken['$value'];
  'color.brightness.pct125': NumberToken['$value'];
  'color.brightness.pct150': NumberToken['$value'];
  'color.brightness.pct200': NumberToken['$value'];
  'border.presets.default': BorderToken['$value'];
  'border.color.default': ColorToken['$value'];
  'border.color.muted': ColorToken['$value'];
  'border.radius.none': DimensionToken['$value'];
  'border.radius.sm': DimensionToken['$value'];
  'border.radius.default': DimensionToken['$value'];
  'border.radius.md': DimensionToken['$value'];
  'border.radius.lg': DimensionToken['$value'];
  'border.radius.xl': DimensionToken['$value'];
  'border.radius.xl2': DimensionToken['$value'];
  'border.radius.xl3': DimensionToken['$value'];
  'border.radius.full': DimensionToken['$value'];
  'border.width.n0': DimensionToken['$value'];
  'border.width.default': DimensionToken['$value'];
  'border.width.n2': DimensionToken['$value'];
  'border.width.n4': DimensionToken['$value'];
  'border.width.n8': DimensionToken['$value'];
  'border.outlineOffset.n0': DimensionToken['$value'];
  'border.outlineOffset.n1': DimensionToken['$value'];
  'border.outlineOffset.n2': DimensionToken['$value'];
  'border.outlineOffset.n4': DimensionToken['$value'];
  'border.outlineOffset.n8': DimensionToken['$value'];
  'border.outlineWidth.n0': DimensionToken['$value'];
  'border.outlineWidth.n1': DimensionToken['$value'];
  'border.outlineWidth.n2': DimensionToken['$value'];
  'border.outlineWidth.n4': DimensionToken['$value'];
  'border.outlineWidth.n8': DimensionToken['$value'];
  'spacing.px': DimensionToken['$value'];
  'spacing.rem.n0': DimensionToken['$value'];
  'spacing.rem.n0half': DimensionToken['$value'];
  'spacing.rem.n1': DimensionToken['$value'];
  'spacing.rem.n1half': DimensionToken['$value'];
  'spacing.rem.n2': DimensionToken['$value'];
  'spacing.rem.n2half': DimensionToken['$value'];
  'spacing.rem.n3': DimensionToken['$value'];
  'spacing.rem.n3half': DimensionToken['$value'];
  'spacing.rem.n4': DimensionToken['$value'];
  'spacing.rem.n5': DimensionToken['$value'];
  'spacing.rem.n6': DimensionToken['$value'];
  'spacing.rem.n7': DimensionToken['$value'];
  'spacing.rem.n8': DimensionToken['$value'];
  'spacing.rem.n9': DimensionToken['$value'];
  'spacing.rem.n10': DimensionToken['$value'];
  'spacing.rem.n11': DimensionToken['$value'];
  'spacing.rem.n12': DimensionToken['$value'];
  'spacing.rem.n14': DimensionToken['$value'];
  'spacing.rem.n16': DimensionToken['$value'];
  'spacing.rem.n20': DimensionToken['$value'];
  'spacing.rem.n24': DimensionToken['$value'];
  'spacing.rem.n28': DimensionToken['$value'];
  'spacing.rem.n32': DimensionToken['$value'];
  'spacing.rem.n36': DimensionToken['$value'];
  'spacing.rem.n40': DimensionToken['$value'];
  'spacing.rem.n44': DimensionToken['$value'];
  'spacing.rem.n48': DimensionToken['$value'];
  'spacing.rem.n52': DimensionToken['$value'];
  'spacing.rem.n56': DimensionToken['$value'];
  'spacing.rem.n60': DimensionToken['$value'];
  'spacing.rem.n64': DimensionToken['$value'];
  'spacing.rem.n72': DimensionToken['$value'];
  'spacing.rem.n80': DimensionToken['$value'];
  'spacing.rem.n96': DimensionToken['$value'];
  'size.percent.pct0': NumberToken['$value'];
  'size.percent.pct5': NumberToken['$value'];
  'size.percent.pct10': NumberToken['$value'];
  'size.percent.pct15': NumberToken['$value'];
  'size.percent.pct20': NumberToken['$value'];
  'size.percent.pct25': NumberToken['$value'];
  'size.percent.pct30': NumberToken['$value'];
  'size.percent.pct35': NumberToken['$value'];
  'size.percent.pct40': NumberToken['$value'];
  'size.percent.pct45': NumberToken['$value'];
  'size.percent.pct50': NumberToken['$value'];
  'size.percent.pct55': NumberToken['$value'];
  'size.percent.pct60': NumberToken['$value'];
  'size.percent.pct65': NumberToken['$value'];
  'size.percent.pct70': NumberToken['$value'];
  'size.percent.pct75': NumberToken['$value'];
  'size.percent.pct80': NumberToken['$value'];
  'size.percent.pct90': NumberToken['$value'];
  'size.percent.pct95': NumberToken['$value'];
  'size.percent.pct100': NumberToken['$value'];
  'size.percent.pct105': NumberToken['$value'];
  'size.percent.pct110': NumberToken['$value'];
  'size.percent.pct125': NumberToken['$value'];
  'size.percent.pct150': NumberToken['$value'];
  'size.degree.deg0': NumberToken['$value'];
  'size.degree.deg1': NumberToken['$value'];
  'size.degree.deg2': NumberToken['$value'];
  'size.degree.deg3': NumberToken['$value'];
  'size.degree.deg6': NumberToken['$value'];
  'size.degree.deg12': NumberToken['$value'];
  'size.degree.deg45': NumberToken['$value'];
  'size.degree.deg90': NumberToken['$value'];
  'size.degree.deg135': NumberToken['$value'];
  'size.degree.deg180': NumberToken['$value'];
  'size.degree.deg225': NumberToken['$value'];
  'size.degree.deg270': NumberToken['$value'];
  'size.degree.deg315': NumberToken['$value'];
  'size.blur.n0': DimensionToken['$value'];
  'size.blur.sm': DimensionToken['$value'];
  'size.blur.default': DimensionToken['$value'];
  'size.blur.md': DimensionToken['$value'];
  'size.blur.lg': DimensionToken['$value'];
  'size.blur.xl': DimensionToken['$value'];
  'size.blur.xl2': DimensionToken['$value'];
  'size.blur.xl3': DimensionToken['$value'];
  'size.lineHeight.none': NumberToken['$value'];
  'size.lineHeight.tight': NumberToken['$value'];
  'size.lineHeight.snug': NumberToken['$value'];
  'size.lineHeight.normal': NumberToken['$value'];
  'size.lineHeight.relaxed': NumberToken['$value'];
  'size.lineHeight.loose': NumberToken['$value'];
  'size.lineHeight.rem.n3': DimensionToken['$value'];
  'size.lineHeight.rem.n4': DimensionToken['$value'];
  'size.lineHeight.rem.n5': DimensionToken['$value'];
  'size.lineHeight.rem.n6': DimensionToken['$value'];
  'size.lineHeight.rem.n7': DimensionToken['$value'];
  'size.lineHeight.rem.n8': DimensionToken['$value'];
  'size.lineHeight.rem.n9': DimensionToken['$value'];
  'size.lineHeight.rem.n10': DimensionToken['$value'];
  'width.screens.sm': DimensionToken['$value'];
  'width.screens.md': DimensionToken['$value'];
  'width.screens.lg': DimensionToken['$value'];
  'width.screens.xl': DimensionToken['$value'];
  'width.screens.xl2': DimensionToken['$value'];
  'width.max.n0': DimensionToken['$value'];
  'width.max.xs': DimensionToken['$value'];
  'width.max.sm': DimensionToken['$value'];
  'width.max.md': DimensionToken['$value'];
  'width.max.lg': DimensionToken['$value'];
  'width.max.xl': DimensionToken['$value'];
  'width.max.xl2': DimensionToken['$value'];
  'width.max.xl3': DimensionToken['$value'];
  'width.max.xl4': DimensionToken['$value'];
  'width.max.xl5': DimensionToken['$value'];
  'width.max.xl6': DimensionToken['$value'];
  'width.max.xl7': DimensionToken['$value'];
  'width.stroke.n0': NumberToken['$value'];
  'width.stroke.n1': NumberToken['$value'];
  'width.stroke.n2': NumberToken['$value'];
  'width.columns.xs': DimensionToken['$value'];
  'width.columns.sm': DimensionToken['$value'];
  'width.columns.md': DimensionToken['$value'];
  'width.columns.lg': DimensionToken['$value'];
  'width.columns.xl': DimensionToken['$value'];
  'width.columns.xl2': DimensionToken['$value'];
  'width.columns.xl3': DimensionToken['$value'];
  'width.columns.xl4': DimensionToken['$value'];
  'width.columns.xl5': DimensionToken['$value'];
  'width.columns.xl6': DimensionToken['$value'];
  'width.columns.xl7': DimensionToken['$value'];
  'shadow.sm': ShadowToken['$value'];
  'shadow.default': ShadowToken['$value'];
  'shadow.default2': ShadowToken['$value'];
  'shadow.md': ShadowToken['$value'];
  'shadow.md2': ShadowToken['$value'];
  'shadow.lg': ShadowToken['$value'];
  'shadow.lg2': ShadowToken['$value'];
  'shadow.xl': ShadowToken['$value'];
  'shadow.xl2': ShadowToken['$value'];
  'shadow.xl2p2': ShadowToken['$value'];
  'shadow.inner': ShadowToken['$value'];
  'font.family.sans': FontFamilyToken['$value'];
  'font.family.serif': FontFamilyToken['$value'];
  'font.family.monospace': FontFamilyToken['$value'];
  'font.size.xs': DimensionToken['$value'];
  'font.size.sm': DimensionToken['$value'];
  'font.size.base': DimensionToken['$value'];
  'font.size.lg': DimensionToken['$value'];
  'font.size.xl': DimensionToken['$value'];
  'font.size.xl2': DimensionToken['$value'];
  'font.size.xl3': DimensionToken['$value'];
  'font.size.xl4': DimensionToken['$value'];
  'font.size.xl5': DimensionToken['$value'];
  'font.size.xl6': DimensionToken['$value'];
  'font.size.xl7': DimensionToken['$value'];
  'font.size.xl8': DimensionToken['$value'];
  'font.size.xl9': DimensionToken['$value'];
  'font.weight.thin': FontWeightToken['$value'];
  'font.weight.extralight': FontWeightToken['$value'];
  'font.weight.light': FontWeightToken['$value'];
  'font.weight.normal': FontWeightToken['$value'];
  'font.weight.medium': FontWeightToken['$value'];
  'font.weight.semibold': FontWeightToken['$value'];
  'font.weight.bold': FontWeightToken['$value'];
  'font.weight.extrabold': FontWeightToken['$value'];
  'font.weight.black': FontWeightToken['$value'];
  'font.text.xs': TypographyToken['$value'];
  'font.text.sm': TypographyToken['$value'];
  'font.text.base': TypographyToken['$value'];
  'font.text.lg': TypographyToken['$value'];
  'font.text.xl': TypographyToken['$value'];
  'font.text.xl2': TypographyToken['$value'];
  'font.text.xl3': TypographyToken['$value'];
  'font.text.xl4': TypographyToken['$value'];
  'font.text.xl5': TypographyToken['$value'];
  'font.text.xl6': TypographyToken['$value'];
  'font.text.xl7': TypographyToken['$value'];
  'font.text.xl8': TypographyToken['$value'];
  'font.text.xl9': TypographyToken['$value'];
  'font.text.letterSpacing.tighter': DimensionToken['$value'];
  'font.text.letterSpacing.tight': DimensionToken['$value'];
  'font.text.letterSpacing.normal': DimensionToken['$value'];
  'font.text.letterSpacing.wide': DimensionToken['$value'];
  'font.text.letterSpacing.wider': DimensionToken['$value'];
  'font.text.letterSpacing.wildest': DimensionToken['$value'];
  'font.text.textDecoThick.n0': DimensionToken['$value'];
  'font.text.textDecoThick.n1': DimensionToken['$value'];
  'font.text.textDecoThick.n2': DimensionToken['$value'];
  'font.text.textDecoThick.n4': DimensionToken['$value'];
  'font.text.textDecoThick.n8': DimensionToken['$value'];
  'font.text.textUnderlineOffset.n0': DimensionToken['$value'];
  'font.text.textUnderlineOffset.n1': DimensionToken['$value'];
  'font.text.textUnderlineOffset.n2': DimensionToken['$value'];
  'font.text.textUnderlineOffset.n4': DimensionToken['$value'];
  'font.text.textUnderlineOffset.n8': DimensionToken['$value'];
  'transition.period.n0': DurationToken['$value'];
  'transition.period.n75': DurationToken['$value'];
  'transition.period.n100': DurationToken['$value'];
  'transition.period.n150': DurationToken['$value'];
  'transition.period.n200': DurationToken['$value'];
  'transition.period.n300': DurationToken['$value'];
  'transition.period.n500': DurationToken['$value'];
  'transition.period.n700': DurationToken['$value'];
  'transition.period.n1000': DurationToken['$value'];
  'transition.timingFunc.default': CubicBezierToken['$value'];
  'transition.timingFunc.linear': CubicBezierToken['$value'];
  'transition.timingFunc.in': CubicBezierToken['$value'];
  'transition.timingFunc.out': CubicBezierToken['$value'];
  'transition.timingFunc.inOut': CubicBezierToken['$value'];
  'zIndex.n0': NumberToken['$value'];
  'zIndex.n10': NumberToken['$value'];
  'zIndex.n20': NumberToken['$value'];
  'zIndex.n30': NumberToken['$value'];
  'zIndex.n40': NumberToken['$value'];
  'zIndex.n50': NumberToken['$value'];
};

export declare const meta: {
  'palette.black': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.black'] };
  };
  'palette.white': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.white'] };
  };
  'palette.gray25': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray25'] };
  };
  'palette.gray50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray50'] };
  };
  'palette.gray100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray100'] };
  };
  'palette.gray200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray200'] };
  };
  'palette.gray300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray300'] };
  };
  'palette.gray400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray400'] };
  };
  'palette.gray500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray500'] };
  };
  'palette.gray600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray600'] };
  };
  'palette.gray700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray700'] };
  };
  'palette.gray800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray800'] };
  };
  'palette.gray900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray900'] };
  };
  'palette.gray950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.gray950'] };
  };
  'palette.slate50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate50'] };
  };
  'palette.slate100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate100'] };
  };
  'palette.slate200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate200'] };
  };
  'palette.slate300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate300'] };
  };
  'palette.slate400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate400'] };
  };
  'palette.slate500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate500'] };
  };
  'palette.slate600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate600'] };
  };
  'palette.slate700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate700'] };
  };
  'palette.slate800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate800'] };
  };
  'palette.slate900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate900'] };
  };
  'palette.slate950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.slate950'] };
  };
  'palette.teal50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal50'] };
  };
  'palette.teal100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal100'] };
  };
  'palette.teal200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal200'] };
  };
  'palette.teal300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal300'] };
  };
  'palette.teal400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal400'] };
  };
  'palette.teal500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal500'] };
  };
  'palette.teal600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal600'] };
  };
  'palette.teal700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal700'] };
  };
  'palette.teal800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal800'] };
  };
  'palette.teal900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.teal900'] };
  };
  'palette.green50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green50'] };
  };
  'palette.green100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green100'] };
  };
  'palette.green200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green200'] };
  };
  'palette.green300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green300'] };
  };
  'palette.green400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green400'] };
  };
  'palette.green500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green500'] };
  };
  'palette.green600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green600'] };
  };
  'palette.green700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green700'] };
  };
  'palette.green800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green800'] };
  };
  'palette.green900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green900'] };
  };
  'palette.green950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.green950'] };
  };
  'palette.blue50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue50'] };
  };
  'palette.blue100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue100'] };
  };
  'palette.blue200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue200'] };
  };
  'palette.blue300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue300'] };
  };
  'palette.blue400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue400'] };
  };
  'palette.blue500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue500'] };
  };
  'palette.blue600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue600'] };
  };
  'palette.blue700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue700'] };
  };
  'palette.blue800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue800'] };
  };
  'palette.blue900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue900'] };
  };
  'palette.blue950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.blue950'] };
  };
  'palette.cyan50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan50'] };
  };
  'palette.cyan100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan100'] };
  };
  'palette.cyan200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan200'] };
  };
  'palette.cyan300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan300'] };
  };
  'palette.cyan400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan400'] };
  };
  'palette.cyan500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan500'] };
  };
  'palette.cyan600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan600'] };
  };
  'palette.cyan700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan700'] };
  };
  'palette.cyan800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan800'] };
  };
  'palette.cyan900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan900'] };
  };
  'palette.cyan950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.cyan950'] };
  };
  'palette.violet50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet50'] };
  };
  'palette.violet100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet100'] };
  };
  'palette.violet200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet200'] };
  };
  'palette.violet300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet300'] };
  };
  'palette.violet400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet400'] };
  };
  'palette.violet500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet500'] };
  };
  'palette.violet600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet600'] };
  };
  'palette.violet700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet700'] };
  };
  'palette.violet800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet800'] };
  };
  'palette.violet900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet900'] };
  };
  'palette.violet950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.violet950'] };
  };
  'palette.purple50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple50'] };
  };
  'palette.purple100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple100'] };
  };
  'palette.purple200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple200'] };
  };
  'palette.purple300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple300'] };
  };
  'palette.purple400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple400'] };
  };
  'palette.purple500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple500'] };
  };
  'palette.purple600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple600'] };
  };
  'palette.purple700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple700'] };
  };
  'palette.purple800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple800'] };
  };
  'palette.purple900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple900'] };
  };
  'palette.purple950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.purple950'] };
  };
  'palette.orange50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange50'] };
  };
  'palette.orange100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange100'] };
  };
  'palette.orange200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange200'] };
  };
  'palette.orange300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange300'] };
  };
  'palette.orange400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange400'] };
  };
  'palette.orange500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange500'] };
  };
  'palette.orange600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange600'] };
  };
  'palette.orange700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange700'] };
  };
  'palette.orange800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange800'] };
  };
  'palette.orange900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange900'] };
  };
  'palette.orange950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.orange950'] };
  };
  'palette.amber50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber50'] };
  };
  'palette.amber100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber100'] };
  };
  'palette.amber200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber200'] };
  };
  'palette.amber300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber300'] };
  };
  'palette.amber400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber400'] };
  };
  'palette.amber500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber500'] };
  };
  'palette.amber600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber600'] };
  };
  'palette.amber700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber700'] };
  };
  'palette.amber800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber800'] };
  };
  'palette.amber900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber900'] };
  };
  'palette.amber950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.amber950'] };
  };
  'palette.yellow50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow50'] };
  };
  'palette.yellow100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow100'] };
  };
  'palette.yellow200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow200'] };
  };
  'palette.yellow300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow300'] };
  };
  'palette.yellow400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow400'] };
  };
  'palette.yellow500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow500'] };
  };
  'palette.yellow600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow600'] };
  };
  'palette.yellow700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow700'] };
  };
  'palette.yellow800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow800'] };
  };
  'palette.yellow900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow900'] };
  };
  'palette.yellow950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.yellow950'] };
  };
  'palette.red50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red50'] };
  };
  'palette.red100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red100'] };
  };
  'palette.red200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red200'] };
  };
  'palette.red300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red300'] };
  };
  'palette.red400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red400'] };
  };
  'palette.red500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red500'] };
  };
  'palette.red600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red600'] };
  };
  'palette.red700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red700'] };
  };
  'palette.red800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red800'] };
  };
  'palette.red900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red900'] };
  };
  'palette.red950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.red950'] };
  };
  'palette.rose50': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose50'] };
  };
  'palette.rose100': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose100'] };
  };
  'palette.rose200': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose200'] };
  };
  'palette.rose300': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose300'] };
  };
  'palette.rose400': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose400'] };
  };
  'palette.rose500': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose500'] };
  };
  'palette.rose600': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose600'] };
  };
  'palette.rose700': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose700'] };
  };
  'palette.rose800': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose800'] };
  };
  'palette.rose900': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose900'] };
  };
  'palette.rose950': ParsedColorToken & {
    $extensions: { mode: (typeof modes)['palette.rose950'] };
  };
  'color.brand.primary': ParsedColorToken;
  'color.brand.light': ParsedColorToken;
  'color.brand.lighter': ParsedColorToken;
  'color.brand.dark': ParsedColorToken;
  'color.brand.darker': ParsedColorToken;
  'color.background.default': ParsedColorToken;
  'color.background.hover': ParsedColorToken;
  'color.background.dark': ParsedColorToken;
  'color.text.body': ParsedColorToken;
  'color.text.muted': ParsedColorToken;
  'color.text.error': ParsedColorToken;
  'color.text.link': ParsedColorToken;
  'color.brightness.pct0': ParsedNumberToken;
  'color.brightness.pct50': ParsedNumberToken;
  'color.brightness.pct75': ParsedNumberToken;
  'color.brightness.pct90': ParsedNumberToken;
  'color.brightness.pct95': ParsedNumberToken;
  'color.brightness.pct100': ParsedNumberToken;
  'color.brightness.pct105': ParsedNumberToken;
  'color.brightness.pct110': ParsedNumberToken;
  'color.brightness.pct125': ParsedNumberToken;
  'color.brightness.pct150': ParsedNumberToken;
  'color.brightness.pct200': ParsedNumberToken;
  'border.presets.default': ParsedBorderToken;
  'border.color.default': ParsedColorToken;
  'border.color.muted': ParsedColorToken;
  'border.radius.none': ParsedDimensionToken;
  'border.radius.sm': ParsedDimensionToken;
  'border.radius.default': ParsedDimensionToken;
  'border.radius.md': ParsedDimensionToken;
  'border.radius.lg': ParsedDimensionToken;
  'border.radius.xl': ParsedDimensionToken;
  'border.radius.xl2': ParsedDimensionToken;
  'border.radius.xl3': ParsedDimensionToken;
  'border.radius.full': ParsedDimensionToken;
  'border.width.n0': ParsedDimensionToken;
  'border.width.default': ParsedDimensionToken;
  'border.width.n2': ParsedDimensionToken;
  'border.width.n4': ParsedDimensionToken;
  'border.width.n8': ParsedDimensionToken;
  'border.outlineOffset.n0': ParsedDimensionToken;
  'border.outlineOffset.n1': ParsedDimensionToken;
  'border.outlineOffset.n2': ParsedDimensionToken;
  'border.outlineOffset.n4': ParsedDimensionToken;
  'border.outlineOffset.n8': ParsedDimensionToken;
  'border.outlineWidth.n0': ParsedDimensionToken;
  'border.outlineWidth.n1': ParsedDimensionToken;
  'border.outlineWidth.n2': ParsedDimensionToken;
  'border.outlineWidth.n4': ParsedDimensionToken;
  'border.outlineWidth.n8': ParsedDimensionToken;
  'spacing.px': ParsedDimensionToken;
  'spacing.rem.n0': ParsedDimensionToken;
  'spacing.rem.n0half': ParsedDimensionToken;
  'spacing.rem.n1': ParsedDimensionToken;
  'spacing.rem.n1half': ParsedDimensionToken;
  'spacing.rem.n2': ParsedDimensionToken;
  'spacing.rem.n2half': ParsedDimensionToken;
  'spacing.rem.n3': ParsedDimensionToken;
  'spacing.rem.n3half': ParsedDimensionToken;
  'spacing.rem.n4': ParsedDimensionToken;
  'spacing.rem.n5': ParsedDimensionToken;
  'spacing.rem.n6': ParsedDimensionToken;
  'spacing.rem.n7': ParsedDimensionToken;
  'spacing.rem.n8': ParsedDimensionToken;
  'spacing.rem.n9': ParsedDimensionToken;
  'spacing.rem.n10': ParsedDimensionToken;
  'spacing.rem.n11': ParsedDimensionToken;
  'spacing.rem.n12': ParsedDimensionToken;
  'spacing.rem.n14': ParsedDimensionToken;
  'spacing.rem.n16': ParsedDimensionToken;
  'spacing.rem.n20': ParsedDimensionToken;
  'spacing.rem.n24': ParsedDimensionToken;
  'spacing.rem.n28': ParsedDimensionToken;
  'spacing.rem.n32': ParsedDimensionToken;
  'spacing.rem.n36': ParsedDimensionToken;
  'spacing.rem.n40': ParsedDimensionToken;
  'spacing.rem.n44': ParsedDimensionToken;
  'spacing.rem.n48': ParsedDimensionToken;
  'spacing.rem.n52': ParsedDimensionToken;
  'spacing.rem.n56': ParsedDimensionToken;
  'spacing.rem.n60': ParsedDimensionToken;
  'spacing.rem.n64': ParsedDimensionToken;
  'spacing.rem.n72': ParsedDimensionToken;
  'spacing.rem.n80': ParsedDimensionToken;
  'spacing.rem.n96': ParsedDimensionToken;
  'size.percent.pct0': ParsedNumberToken;
  'size.percent.pct5': ParsedNumberToken;
  'size.percent.pct10': ParsedNumberToken;
  'size.percent.pct15': ParsedNumberToken;
  'size.percent.pct20': ParsedNumberToken;
  'size.percent.pct25': ParsedNumberToken;
  'size.percent.pct30': ParsedNumberToken;
  'size.percent.pct35': ParsedNumberToken;
  'size.percent.pct40': ParsedNumberToken;
  'size.percent.pct45': ParsedNumberToken;
  'size.percent.pct50': ParsedNumberToken;
  'size.percent.pct55': ParsedNumberToken;
  'size.percent.pct60': ParsedNumberToken;
  'size.percent.pct65': ParsedNumberToken;
  'size.percent.pct70': ParsedNumberToken;
  'size.percent.pct75': ParsedNumberToken;
  'size.percent.pct80': ParsedNumberToken;
  'size.percent.pct90': ParsedNumberToken;
  'size.percent.pct95': ParsedNumberToken;
  'size.percent.pct100': ParsedNumberToken;
  'size.percent.pct105': ParsedNumberToken;
  'size.percent.pct110': ParsedNumberToken;
  'size.percent.pct125': ParsedNumberToken;
  'size.percent.pct150': ParsedNumberToken;
  'size.degree.deg0': ParsedNumberToken;
  'size.degree.deg1': ParsedNumberToken;
  'size.degree.deg2': ParsedNumberToken;
  'size.degree.deg3': ParsedNumberToken;
  'size.degree.deg6': ParsedNumberToken;
  'size.degree.deg12': ParsedNumberToken;
  'size.degree.deg45': ParsedNumberToken;
  'size.degree.deg90': ParsedNumberToken;
  'size.degree.deg135': ParsedNumberToken;
  'size.degree.deg180': ParsedNumberToken;
  'size.degree.deg225': ParsedNumberToken;
  'size.degree.deg270': ParsedNumberToken;
  'size.degree.deg315': ParsedNumberToken;
  'size.blur.n0': ParsedDimensionToken;
  'size.blur.sm': ParsedDimensionToken;
  'size.blur.default': ParsedDimensionToken;
  'size.blur.md': ParsedDimensionToken;
  'size.blur.lg': ParsedDimensionToken;
  'size.blur.xl': ParsedDimensionToken;
  'size.blur.xl2': ParsedDimensionToken;
  'size.blur.xl3': ParsedDimensionToken;
  'size.lineHeight.none': ParsedNumberToken;
  'size.lineHeight.tight': ParsedNumberToken;
  'size.lineHeight.snug': ParsedNumberToken;
  'size.lineHeight.normal': ParsedNumberToken;
  'size.lineHeight.relaxed': ParsedNumberToken;
  'size.lineHeight.loose': ParsedNumberToken;
  'size.lineHeight.rem.n3': ParsedDimensionToken;
  'size.lineHeight.rem.n4': ParsedDimensionToken;
  'size.lineHeight.rem.n5': ParsedDimensionToken;
  'size.lineHeight.rem.n6': ParsedDimensionToken;
  'size.lineHeight.rem.n7': ParsedDimensionToken;
  'size.lineHeight.rem.n8': ParsedDimensionToken;
  'size.lineHeight.rem.n9': ParsedDimensionToken;
  'size.lineHeight.rem.n10': ParsedDimensionToken;
  'width.screens.sm': ParsedDimensionToken;
  'width.screens.md': ParsedDimensionToken;
  'width.screens.lg': ParsedDimensionToken;
  'width.screens.xl': ParsedDimensionToken;
  'width.screens.xl2': ParsedDimensionToken;
  'width.max.n0': ParsedDimensionToken;
  'width.max.xs': ParsedDimensionToken;
  'width.max.sm': ParsedDimensionToken;
  'width.max.md': ParsedDimensionToken;
  'width.max.lg': ParsedDimensionToken;
  'width.max.xl': ParsedDimensionToken;
  'width.max.xl2': ParsedDimensionToken;
  'width.max.xl3': ParsedDimensionToken;
  'width.max.xl4': ParsedDimensionToken;
  'width.max.xl5': ParsedDimensionToken;
  'width.max.xl6': ParsedDimensionToken;
  'width.max.xl7': ParsedDimensionToken;
  'width.stroke.n0': ParsedNumberToken;
  'width.stroke.n1': ParsedNumberToken;
  'width.stroke.n2': ParsedNumberToken;
  'width.columns.xs': ParsedDimensionToken;
  'width.columns.sm': ParsedDimensionToken;
  'width.columns.md': ParsedDimensionToken;
  'width.columns.lg': ParsedDimensionToken;
  'width.columns.xl': ParsedDimensionToken;
  'width.columns.xl2': ParsedDimensionToken;
  'width.columns.xl3': ParsedDimensionToken;
  'width.columns.xl4': ParsedDimensionToken;
  'width.columns.xl5': ParsedDimensionToken;
  'width.columns.xl6': ParsedDimensionToken;
  'width.columns.xl7': ParsedDimensionToken;
  'shadow.sm': ParsedShadowToken;
  'shadow.default': ParsedShadowToken;
  'shadow.default2': ParsedShadowToken;
  'shadow.md': ParsedShadowToken;
  'shadow.md2': ParsedShadowToken;
  'shadow.lg': ParsedShadowToken;
  'shadow.lg2': ParsedShadowToken;
  'shadow.xl': ParsedShadowToken;
  'shadow.xl2': ParsedShadowToken;
  'shadow.xl2p2': ParsedShadowToken;
  'shadow.inner': ParsedShadowToken;
  'font.family.sans': ParsedFontFamilyToken;
  'font.family.serif': ParsedFontFamilyToken;
  'font.family.monospace': ParsedFontFamilyToken;
  'font.size.xs': ParsedDimensionToken;
  'font.size.sm': ParsedDimensionToken;
  'font.size.base': ParsedDimensionToken;
  'font.size.lg': ParsedDimensionToken;
  'font.size.xl': ParsedDimensionToken;
  'font.size.xl2': ParsedDimensionToken;
  'font.size.xl3': ParsedDimensionToken;
  'font.size.xl4': ParsedDimensionToken;
  'font.size.xl5': ParsedDimensionToken;
  'font.size.xl6': ParsedDimensionToken;
  'font.size.xl7': ParsedDimensionToken;
  'font.size.xl8': ParsedDimensionToken;
  'font.size.xl9': ParsedDimensionToken;
  'font.weight.thin': ParsedFontWeightToken;
  'font.weight.extralight': ParsedFontWeightToken;
  'font.weight.light': ParsedFontWeightToken;
  'font.weight.normal': ParsedFontWeightToken;
  'font.weight.medium': ParsedFontWeightToken;
  'font.weight.semibold': ParsedFontWeightToken;
  'font.weight.bold': ParsedFontWeightToken;
  'font.weight.extrabold': ParsedFontWeightToken;
  'font.weight.black': ParsedFontWeightToken;
  'font.text.xs': ParsedTypographyToken;
  'font.text.sm': ParsedTypographyToken;
  'font.text.base': ParsedTypographyToken;
  'font.text.lg': ParsedTypographyToken;
  'font.text.xl': ParsedTypographyToken;
  'font.text.xl2': ParsedTypographyToken;
  'font.text.xl3': ParsedTypographyToken;
  'font.text.xl4': ParsedTypographyToken;
  'font.text.xl5': ParsedTypographyToken;
  'font.text.xl6': ParsedTypographyToken;
  'font.text.xl7': ParsedTypographyToken;
  'font.text.xl8': ParsedTypographyToken;
  'font.text.xl9': ParsedTypographyToken;
  'font.text.letterSpacing.tighter': ParsedDimensionToken;
  'font.text.letterSpacing.tight': ParsedDimensionToken;
  'font.text.letterSpacing.normal': ParsedDimensionToken;
  'font.text.letterSpacing.wide': ParsedDimensionToken;
  'font.text.letterSpacing.wider': ParsedDimensionToken;
  'font.text.letterSpacing.wildest': ParsedDimensionToken;
  'font.text.textDecoThick.n0': ParsedDimensionToken;
  'font.text.textDecoThick.n1': ParsedDimensionToken;
  'font.text.textDecoThick.n2': ParsedDimensionToken;
  'font.text.textDecoThick.n4': ParsedDimensionToken;
  'font.text.textDecoThick.n8': ParsedDimensionToken;
  'font.text.textUnderlineOffset.n0': ParsedDimensionToken;
  'font.text.textUnderlineOffset.n1': ParsedDimensionToken;
  'font.text.textUnderlineOffset.n2': ParsedDimensionToken;
  'font.text.textUnderlineOffset.n4': ParsedDimensionToken;
  'font.text.textUnderlineOffset.n8': ParsedDimensionToken;
  'transition.period.n0': ParsedDurationToken;
  'transition.period.n75': ParsedDurationToken;
  'transition.period.n100': ParsedDurationToken;
  'transition.period.n150': ParsedDurationToken;
  'transition.period.n200': ParsedDurationToken;
  'transition.period.n300': ParsedDurationToken;
  'transition.period.n500': ParsedDurationToken;
  'transition.period.n700': ParsedDurationToken;
  'transition.period.n1000': ParsedDurationToken;
  'transition.timingFunc.default': ParsedCubicBezierToken;
  'transition.timingFunc.linear': ParsedCubicBezierToken;
  'transition.timingFunc.in': ParsedCubicBezierToken;
  'transition.timingFunc.out': ParsedCubicBezierToken;
  'transition.timingFunc.inOut': ParsedCubicBezierToken;
  'zIndex.n0': ParsedNumberToken;
  'zIndex.n10': ParsedNumberToken;
  'zIndex.n20': ParsedNumberToken;
  'zIndex.n30': ParsedNumberToken;
  'zIndex.n40': ParsedNumberToken;
  'zIndex.n50': ParsedNumberToken;
};

export declare const modes: {
  'palette.black': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.white': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray25': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.gray950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.slate950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.teal900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.green950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.blue950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.cyan950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.violet950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.purple950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.orange950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.amber950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.yellow950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.red950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose50': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose100': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose200': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose300': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose400': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose500': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose600': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose700': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose800': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose900': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
  'palette.rose950': {
    light: ColorToken['$value'];
    dark: ColorToken['$value'];
  };
};

export declare function token<K extends keyof typeof tokens>(
  tokenID: K,
  modeName?: never,
): (typeof tokens)[K];
export declare function token<
  K extends keyof typeof modes,
  M extends keyof (typeof modes)[K],
>(tokenID: K, modeName: M): (typeof modes)[K][M];
