export { PMMinimalApp as A11PMMinimalApp } from './a1-starter/a11-minimal';
export { PMExampleSetupBasicEditor as A12PMExampleSetupBasicEditor } from './a1-starter/a12-example-setup-basic-editor';
export { CustomElementEditor as A13CustomElementEditor } from './a1-starter/a13-custom-element-and-formatting';
export { CustomMenuToolbar as A14CustomMenuToolbar } from './a1-starter/a14-menu-toolbar';
export { EditorTooltipPopover as A15EditorTooltipPopover } from './a1-starter/a15-tooltip';
export { CustomSchemaBlockGroupLink as A16CustomSchemaBlockGroupLink } from './a1-starter/a16-custom-schema-link';
export { ImageUpload as A17ImageUpload } from './a1-starter/a17-image-upload';
export { MarkdownViewsSwitcher as A18MarkdownViewsSwitcher } from './a1-starter/a18-markdown-views-switcher';
export { Footnote as A1b1Footnote } from './a1-starter/a1b1-footnote';
export { Lint as A1b2Lint } from './a1-starter/a1b2-lint';
export { TrackChangesMinimal as A1b3TrackChanges } from './a1-starter/a1b3-track-changes';
export { ProseMirrorCollabBasic as A1b4ProseMirrorCollabBasic } from './a1-starter/a1b4-collab-basic';
export { PMCollabMinimalApp as A1b5ProseMirrorCollabMinimal } from '../../prosemirror-collab-minimal/client/collab-minimal-app';
// export { TeemuApp as A1b5TeemuApp } from '../teemu-examples/index';
// export { Footnote2 as A1b1Footnote2 } from './a1-starter/a1b1-footnote2';
// export { InlineToolbarApp as A22InlineToolbarApp } from './a2-features/a22-inline-toolbar';
// export { InlineLinkButtonApp as A23InlineLinkButtonApp } from './a2-features/a23-inline-link-button';
// export { SlateWrappedInContenteditableApp as A71InlineLinkButtonApp } from './a7-issues/a71-slate-wrapped-in-contenteditable';
