// actions names for repo/files manager
export const REFRESH_FILES_FOR_PATH = 'REFRESH_FILES_FOR_PATH';
export const SET_IS_REPO_DATA_LOADED = 'SET_IS_REPO_DATA_LOADED';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const SET_MSG_OPTION = 'SET_MSG_OPTION';
export const CREATE_FOLDER_SUCCESS = 'CREATE_FOLDER_SUCCESS';
export const CREATE_FILE_SUCCESS = 'CREATE_FILE_SUCCESS';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REFRESH_ID = 'REFRESH_ID';
export const RENAME_COMPLETED = 'RENAME_COMPLETED';
export const RENAME_ITEM_START = 'RENAME_ITEM_START';
export const RENAME_ITEM_SUCCESS = 'RENAME_ITEM_SUCCESS';

export const MENU_PADDING = 'MENU_PADDING';
export const HIDE_LIST_ITEM_ACTIONS_MENU = 'HIDE_LIST_ITEM_ACTIONS_MENU';
export const SHOW_LIST_ITEM_ACTIONS_MENU = 'SHOW_LIST_ITEM_ACTIONS_MENU';

export const SET_REPO_VIEW_TYPE = 'SET_REPO_VIEW_TYPE';
export const SET_MATERIAL_FILE_TYPE = 'SET_MATERIAL_FILE_TYPE';
export const VIEW_MATERIAL_FILE = 'VIEW_MATERIAL_FILE';

export const ENABLE_MSG = 'ENABLE_MSG';
export const DISABLE_MSG = 'DISABLE_MSG';
export const LOGOUT_REPO = 'LOGOUT_REPO';

export const DELETE_EDITOR_ITEM = 'DELETE_EDITOR_ITEM';
export const SAVE_EDITOR_ITEM = 'SAVE_EDITOR_ITEM';
